### ISSUE TITLE
using unitQuaternion "[0, 0, 0, 0]" results in error "normalized result is not a number"

### ISSUE THREAD

**Issue by fc** [CesiumGS/cesium#10033]
I was just doing some manual testing with a sandcastle with `unitQuaternion`.  I thought this would just leave the model at its default orientation but instead it lead to an error:

This code
```
    "orientation" : {
        "unitQuaternion" : [0, 0, 0, 0]
    }
```

Leads to this error:
```
DeveloperError: normalized result is not a number

Error
    at new DeveloperError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:83:13)
    at Function.Cartesian3.normalize (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:2135:13)
    at Ellipsoid.geodeticSurfaceNormal (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:3709:23)
    at Object.resultat [as eastNorthUpToFixedFrame] (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:30704:21)
    at Camera.lookAt (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:273255:32)
    at Camera.viewBoundingSphere (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:274468:10)
    at EntityView.update (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:243497:16)
    at updateTrackedEntity (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:354517:24)
    at Viewer._postRender (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:354296:5)
    at Event.raiseEvent (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:17244:22)
```

Sandcastle example:
https://sandcastle.cesium.com/index.html#c=bVNdj9owEPwrqzyBRB24Plx15VCv0IdKd+pVSH0oQZVxlmDVsZE/oFzFf+86DoEeR4A4O7sz4/Vmxy2Il1rBPSwKDfA3/gHI8g6KrDQi1Kh9kQ1SWPMaIzD9+fQIT6ZE1UE7tE4aHdERG7bh4+CKk0srLF97qP8r75jRyVDDg7QdtDVO+oa6JQIQ3HpTWb7dSDHDyiK6O1i8u70dwHv6jYb0Wbblx/be6F1wVMqvoyJj+ZzXW4Uz7nneZLk82SAX7eoXLVmlVp0pACe4Iss3bNiFaqllHepn+QfVXL4QOrr58MpGkRkrqac8bqnI4MJRBIOW/nvgHq0+4YvhANrvsuUqdLwS6fJjXO/oHHcS92jpJDXuIflmP5pYr8hE8zw1pCw1xu4mYbcxQZUPZJxE78DbgER67HesJbVlboIV+GxNLR2SQFJiZ8gxXpa9yNfqTmmmZh3MlOFlL85Zv9CJ+oo2FjO/Qd1bBy1id6B3Tuqf2tRKe8vFbyy/aC/9gRydMxnGmCRLFfrPh6/JVuru6+FLSDREvew3DgxZsHvyc2EDrTW2c7CXujR7RqdvfQu1BM3GskE2dv6gcHLS/STrrbEeglU9mjaPNG3UbJevAu3BM+FcYgAY55el41Lu6LW5f+P0QCjuHCHroJpZK7LJOKf8q9LYeqmrb/SCKn6IaZvR5DEFGWPjnB7frvTGqBW3F8wp4x8

**Comment by fc** [comment]
Closing...somehow I created a duplicate??

**Comment by ptrgags** [comment]
The identity quaternion is `[0, 0, 0, 1]` with 1 in the `w` component. `[0, 0, 0, 0]` is a null quaternion (length 0), not a unit quaternion.

Unit quaternions are of the form:

```
x = sin(theta/2) * axis_x
y = sin(theta/2) * axis_y
z = sin(theta/2) * axis_z
w = cos(theta/2)

where:
- axis is a unit vector 
- theta is the rotation angle
```
When theta = 0 (no rotation), you get `[0, 0, 0, 1]`.

See also the [Quaternion docs](https://cesium.com/learn/cesiumjs/ref-doc/Quaternion.html). In particular, `Cesium.Quaternion.fromAxisAngle()` can be used create a quaternion, and `Cesium.Quaternion.pack()` can turn the result into an array if you're using CZML

[Updated Sandcastle](https://sandcastle.cesium.com/index.html#c=bVNdj9owEPwrqzyBRB24Plx15VCv0IdKd+pVSH0oQZVxlmDVsZE/oFzFf+86DoEeR4A4O7sz4/Vmxy2Il1rBPSwKDfA3/gHI8g6KrDQi1Kh9kQ1SWPMaIzD9+fQIT6ZE1UE7tE4aHdERG7bh4+CKk0srLF97qP8r75jRyVDDg7QdtDVO+oa6JQIQ3HpTWb7dSDHDyiK6O1i8u70dwHv6jYb0Wbblx/be6F1wVMqvoyJj+ZzXW4Uz7nneZLk82SAX7eoXLVmlVp0pACe4Iss3bNiFaqllHepn+QfVXL4QOrr58MpGkRkrqac8bqnI4MJRBIOW/nvgHq0+4YvhANJ3tGy5Ch2vRLr8GNc7OsedxD1aOkmNe0i+2Y8m1isy0TxPDSlLjbG7SdhtTFDlAxkn0TvwNiCRHvsda0ltmZtgBT5bU0uHJJCU2BlyjJdlL/K1ulOaqVkHM2V42Ytz1i90or6ijcXMb1D31kGL2B3onZP6pza10t5y8RvLL9pLfyBH50yGMSbJUoX+8+FrspW6+3r4EhINUS/7jQNDFuye/FzYQGuN7RzspS7NntHpW99CLUGzsWyQjZ0/KJycdD/Jemush2BVj6bNI00bNdvlq0B78Ew4lxgAxvll6biUO3pt7t84PRCKO0fIOqhm1opsMs4p/6o0tl7q6hu9oIofYtpmNHlMQcbYOKfHtyu9MWrF7QVzyvgH)
