### ISSUE TITLE
Recent Draco changes cause spec failures

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#10154]
I noticed that some model loading specs are failing on `main` when I run things locally. These might not have been caught by Travis since they are WebGL tests.

This might be related to the #10126?

Browser: 
 - Chrome 98.0.4758 (launched via VSCode)
 - Firefox 97.0

Operating System: Kbuntu 18.04

Error stack trace from the spec `Scene/GltfLoader loads Duck`

```
Failed: promise rejected: RuntimeError: Failed to load glTF
Failed to load vertex buffer
Failed to load Draco
Cannot read properties of undefined (reading '__destroy__')
Error
    at new RuntimeError (http://localhost:8080/Source/Core/RuntimeError.js:38:11)
    at GltfLoader.ResourceLoader.getError (http://localhost:8080/Source/Scene/ResourceLoader.js:94:10)
    at handleError (http://localhost:8080/Source/Scene/GltfLoader.js:244:22)
    at http://localhost:8080/Source/Scene/GltfLoader.js:1505:7
    at Promise.then (http://localhost:8080/Source/ThirdParty/when.js:217:33)
    at http://localhost:8080/Source/ThirdParty/when.js:297:13
    at processQueue (http://localhost:8080/Source/ThirdParty/when.js:647:4)
    at _resolve (http://localhost:8080/Source/ThirdParty/when.js:333:4)
    at promiseReject (http://localhost:8080/Source/ThirdParty/when.js:366:11)
    at Promise.then (http://localhost:8080/Source/ThirdParty/when.js:217:33)
```

CC @ebogo1

**Comment by ptrgags** [comment]
:facepalm: I forgot to run `npm install`... I'll see myself out.
