### ISSUE TITLE
Support sparse accessors in ModelExperimental

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#10284]
The old `Model` class didn't handle [sparse accessors](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#sparse-accessors) from the glTF spec. For better spec compliance, the new `ModelExperimental` should add this.

Not sure the exact scope of how to implement this, but some thoughts:
* Certainly `GltfLoader` (or related loaders) would need more parsing logic for sparse accessors
* If it's possible, handle this completely at load time so ModelComponents and runtime code such as the `GeometryPipelineStage` don't need to worry about whether the accessor was sparse or dense.

**Comment by j9liu** [comment]
This would also be useful for animation with morph targets, since the weights are packed per keyframe. It gets even more cumbersome to pull the data when `CUBICSPLINE` interpolation is involved, since there are three values per morph weight per keyframe.

**Comment by ggetz** [comment]
In https://github.com/CesiumGS/cesium/issues/11961, @mramato pointed out a glTF which fails to load, and @javagl Identified lack of support for sparse accessors as the cause for the failure.

> [house.glb.txt](https://github.com/CesiumGS/cesium/files/15138348/house.glb.txt) is a draco encoded glTF model that loads fine in all viewers I tried except for CesiumJS. It validates cleanly with no errors.

> When loaded into CesiumJS, it reports:

```
RuntimeError: Failed to load model: ../../SampleData/models/house.glb
Failed to load glTF
One of options.bufferViewId and options.draco must be defined.
```

> ... the way CesiumJS is failing here is not very useful and a clear error message or warning about lack of sparse accessors would be the least we could do. But it definitely bugs me that there is part of the glTF standard we seem to not support, especially since tools like gltf-transform's optimize function produces sparse accessors where applicable.

> @ggetz @lilleyse What is the level of effort to support them?

**Comment by ggetz** [comment]
> What is the level of effort to support them?

Correct me if I'm wrong @lilleyse, but supporting sparse accessors is a matter of updating the loader parsing and shouldn't be complex to support.

**Comment by lilleyse** [comment]
Yeah it seems pretty straightforward. The simplest approach would be to expand the sparse accessor at load time.

**Comment by javagl** [comment]
An example that I created for https://github.com/CesiumGS/cesium/pull/12379 : 

[MorphTestWithSparseAccessors 2024-12-21.zip](https://github.com/user-attachments/files/18218852/MorphTestWithSparseAccessors.2024-12-21.zip)

It uses an artificially and intentionally sparse morph target for the `POSITION` attribute, and should look like this:

![Cesium Sparse Example](https://github.com/user-attachments/assets/69f9f05f-2a31-433c-867d-79e792f7caa5)

It currently bails out with this message:

```
An error occurred while rendering.  Rendering has stopped.
DeveloperError: attribute.value.length must be in the range [1, 4].
Error
    at new DeveloperError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:9080:13)
    at addAttribute (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:34733:15)
    at new VertexArray (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:34863:7)
    at buildDrawCommandForModel (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:106182:25)
    at ModelDrawCommands.buildModelDrawCommand (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:106154:21)
    at ModelSceneGraph.buildDrawCommands (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:106589:55)
    at buildDrawCommands (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:109707:25)
    at Model.update (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:109530:5)
    at PrimitiveCollection.update (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:147560:21)
    at updateAndRenderPrimitives (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:241551:23)
```

**Comment by javagl** [comment]
Things like https://github.com/CesiumGS/cesium/blob/47b5d295facaca795381bf607b78cc60c643fd85/packages/engine/Source/Scene/Model/MorphTargetsPipelineStage.js#L65 should be tracked in an issue, and *at least* generate a warning instead of failing silently or even "crashing silently"...

**Comment by ggetz** [comment]
Also reported in https://github.com/CesiumGS/cesium/issues/12162
