### ISSUE TITLE
Program failed to link. Qt 5.15.3 / Ubuntu 22.04

### ISSUE THREAD

**Issue by srcejon** [CesiumGS/cesium#10652]
I get the error:

    RuntimeError: Program failed to link.  Link log: error: Too many combined image uniforms, shader storage  buffers and fragment outputs

    Error
        at new RuntimeError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:15446:13)
        at createAndLinkProgram (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:69612:13)
        at reinitialize (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:69772:21)
        at initialize2 (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:69767:5)
        at ShaderProgram._bind (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:69826:5)
        at beginDraw (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:176817:19)
        at Context.draw (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:176903:5)
        at DrawCommand.execute (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:67592:13)
        at executeCommand (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:210986:15)
        at executeTranslucentCommandsSortedMRT (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:199987:7)
        
Sandcastle example: https://sandcastle.cesium.com/?src=3D%20Models.html

Browser: Chrome embedded in Qt 5.15.3

Operating System: Ubuntu 22.04 running as WMWorkstation 16.2.4 guest

Cesium: 1.96 (and earlier)

The simplest sandcastle demo works OK (https://sandcastle.cesium.com/) - just get the problem when switching to the 3D models.

Here's the report showing resources from http://webglreport.com/ I saw requested in another bug.

![image](https://user-images.githubusercontent.com/57259258/183381055-dba8f63e-4604-4264-9c6a-d5a74f442fee.png)

The 3D model sandcastle runs OK in the desktop version of Chrome:

![image](https://user-images.githubusercontent.com/57259258/183383196-b5d08084-e0f1-4401-b2a3-348bef92116a.png)

And I don't see this problem when running under Ubuntu 21.10 embedded in the same Qt application. However, in that case, webglreport.com reports that WebGL 2 is disabled in the embedded version of Chrome.

![image](https://user-images.githubusercontent.com/57259258/183381447-5591007c-3f2b-4a5e-819c-99203fe4c597.png)

So seems to be specific to the combination of the version of Chrome embedded in Qt when WebGL 2 acceleration is enabled and the graphics driver.

**Comment by ggetz** [comment]
Thanks for the WebGL report screenshots, @srcejon!

I'm not very familiar with running Cesium on Chrome embedded in Qt. Maybe an addition to this issue, it reach out on the [forum](https://community.cesium.com) to see if any members of the community have any insights?

**Comment by srcejon** [comment]
The problem appears to be able to be worked around with, by setting:

viewer.scene.logarithmicDepthBuffer = false;

This thread: https://groups.google.com/g/cesium-dev/c/ZNuE86hddLA, suggests it may help by reducing the number of varyings (although Max Varying Vectors seems to be the same in the above reports - but I don't really know if that's the same thing)

**Comment by ggetz** [comment]
Interesting. Are you running multiple Cesium views, or potentially running other WebGL applications simultaneously?

I would hesitate to label this as a bug in CesiumJS as it points to WebGL limitations within the Chrome instance embedded in Qt.

**Comment by srcejon** [comment]
No - just the one view.

It may be a problem with Chrome/QT, but I think we'd need to narrow it down a bit more.

Is there any way to find out the specific resource that isn't getting allocated?

Is there a list of the minimum resources Cesium should need?

**Comment by srcejon** [comment]
Looks like the error message comes from Mesa: https://gitlab.freedesktop.org/mesa/mesa/-/blob/22.0/src/compiler/glsl/linker.cpp

if (total_image_units + fragment_outputs + total_shader_storage_blocks >
       consts->MaxCombinedShaderOutputResources)
      linker_error(prog, "Too many combined image uniforms, shader storage "
                         " buffers and fragment outputs\n");

Mesa seems to export consts->MaxCombinedShaderOutputResources as gl_MaxCombinedShaderOutputResources and gl_MaxCombinedImageUnitsAndFragmentOutputs. However, there aren't MAX_COMBINED_SHADER_OUTPUT_RESOURCES or MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS in Cesium's WebGLConstants.js

**Comment by ggetz** [comment]
I'm closing this issue due to inactivity. If you believe this is still an issue, please feel free to re-open. Thanks!
