### ISSUE TITLE
flyTo with up and direction throws DeveloperError

### ISSUE THREAD

**Issue by angrycat9000** [CesiumGS/cesium#10704]
Calling `camera.flyTo` with up and direction throws a `DeveloperError`: 

> Uncaught DeveloperError: left is required.
Error
    at new DeveloperError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:12548:13)
    at CesiumMath.equalsEpsilon (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:12833:13)
    at Cartesian3.equalsEpsilon (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:13345:94)
    at Object.resultat [as eastNorthUpToFixedFrame] (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:25112:32)
    at directionUpToHeadingPitchRoll (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:179757:45)
    at Camera.flyTo (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:180960:21)
    at window.startup (<anonymous>:19:21)
    at <anonymous>:28:12
    at HTMLScriptElement.loadScript (https://sandcastle.cesium.com/CesiumSandcastle.js:681:24) (on line 12833 of https://sandcastle.cesium.com/CesiumUnminified/Cesium.js)

[Documentation](https://cesium.com/learn/cesiumjs/ref-doc/Camera.html#flyTo) indicates that only an `up` and `direction` is required.  

> An object that contains either direction and up properties or heading, pitch and roll properties. 

[Sandcastle example](https://sandcastle.cesium.com/#c=dVLLbhshFP0VNKuJ5DK8H7FjVfK2UqW26mo2BJMEFYMF2JEb5d/LeJrIadIFEvdwz+MCNsVSwdG7R5fBDYjuEWxc8Ycd/HnG+rGz53qTYjU+ujx2V8sxjtGemVtXqo+m+hTf0r85W028D64nkDGmGcMKMS6IknQxRgQFwVQzjiSimAglXkFFEWGUEY61auBMJ1pgwTjHmPM3/j43o3fuG5Nr25lIezCpUoEVkappSEFZUwWfEOQES8wlp6iloGIym1BFsCBEcq2F1OzS7LD/rwtqKQXHLbhoVpRzNqtRSTnTmhHWBlDngRBUmCJJBNZUEymlmD3mR4DFuuigNTuXDbwLpx+pf2p5L296yg9S9q49yVRfg6fXe1i0lM9jfJ40u0U3dsup+WUBsCr1FNx6LgD47Hf7lNtoOfQQDtXt9sG0oYbbg/3lKrSlXC3/ModL6mrrj8Bvbz74H8AGU0o7uTuE8N3/dmO3Xg2t/x01JLP18f7r0eVgTlPbA15/mUEI4Wpo5cfMmlK4Nfkf5T8)

Browser: Chrome

Operating System: Mac OS

**Comment by ggetz** [comment]
Thanks @angrycat9000. The error was not from error checking specific for `flyTo`, but was occurring due to an error further down the stack. Fix is in https://github.com/CesiumGS/cesium/pull/10705.
