### ISSUE TITLE
cesium 1.99 source build error

### ISSUE THREAD

**Issue by super3s1988** [CesiumGS/cesium#10898]
**I download cesium source and build it,when i use "npm run release" commond ,report error:**

> cesium@1.99.0 prepare D:\work\code\source\cesium-1.99
> gulp prepare && husky install

D:\work\code\source\cesium-1.99\gulpfile.js:2
import { writeFileSync, copyFileSync, readFileSync, existsSync } from "fs";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at requireOrImport (D:\work\code\source\cesium-1.99\node_modules\gulp\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11)
    at execute (D:\work\code\source\cesium-1.99\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js:37:3)
    at Liftoff.handleArguments (D:\work\code\source\cesium-1.99\node_modules\gulp\node_modules\gulp-cli\index.js:211:24)
    at Liftoff.execute (D:\work\code\source\cesium-1.99\node_modules\liftoff\index.js:201:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cesium@1.99.0 prepare: `gulp prepare && husky install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cesium@1.99.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by ggetz** [comment]
Hi there, thanks for the report. What version of node are you using?

For example:

```sh
$ node -v
v16.15.0
```

**Comment by super3s1988** [comment]
> Hi there, thanks for the report. What version of node are you using?
> 
> For example:
> 
> ```shell
> $ node -v
> v16.15.0
> ```

v12.13.0

**Comment by ggetz** [comment]
Thanks @super3s1988. The [minimum NodeJS version we recommend is NodeJS 14](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/BuildGuide#build-the-code). However, 16 and even 18 are more recent LTS versions. Is it possible to upgrade your version of NodeJS?

**Comment by super3s1988** [comment]
> Thanks @super3s1988. The [minimum NodeJS version we recommend is NodeJS 14](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/BuildGuide#build-the-code). However, 16 and even 18 are more recent LTS versions. Is it possible to upgrade your version of NodeJS?

 thank you for your reply,after i update the nodejs to 18,the error is disappear.
