### ISSUE TITLE
Large ellipsoid causes DeveloperError: All attribute lists must have the same number of attributes.

### ISSUE THREAD

**Issue by stewienj** [CesiumGS/cesium#10903]
I am getting an error that stops rendering. The message is "DeveloperError: All attribute lists must have the same number of attributes."

Sandcastle example: [Simple large ellipsoid example](https://sandcastle.cesium.com/#c=hZJta9swEMe/yuFXDmSys4TBkjQspO/2BF0pDPRGsa/NMUlnpHOydvS7T7abNe3CZtChO9/vf7qTKvZRYE94wAAX4PEAG4zUOnXTx3KdVb2/YS+GPAadjRbaaz8wCr2QEEZl6jr/pT2ANw7noLNrbsD4GrYswg6qVoBb0dm4S2o4Joz9/FhuY4KknfFTdRvYXeJdQIz5m0n5VpVjmJWdnczK9Kly1GugtdREpnoOfWGAYGqi+WkXz7L59H1ZDvgYzu8HWQDyqc+rf2r14JM5Yo48uX5S+Ketz0Z2SrgTMz7m706qOPPzf+mT2Yt8wUDGPo+MLQd1ub76uPm+/qIOJLu1bXYmL9X0CKWJW+oKSGixjz0m+/jiCh+Y3TXnry50tMjGmc4WHXNcAMso9xZXgwPwgVzDQaANNleqEHSNTceMxbatfqCoKsbR4oksTtFlTXug+uLM84LKmhjTn9vW2m/0gDpbLYuU/xdqOc3J333dY7DmvkvbTVafhqBSalkk9zwpzHZrwivl3w)

Browser: Microsoft Edge version 107

Operating System: Windows 10 x64 21H2

Cesium version: 1.99

Reproducing this error depends on the position and orientation of the ellipse, and the number of slice partions. For example below is the code from the sandcastle example above, if you set slicePartitions to 141 the error goes away, but setting it to 146 brings the error back.
```
const viewer = new Cesium.Viewer("cesiumContainer");

viewer.entities.add({
  name: "Top and bottom cut out",
  position: Cesium.Cartesian3.fromDegrees(-102.0, 40.0, 140000.0),
  ellipsoid: {
    radii: new Cesium.Cartesian3(39000000.0, 39000000.0, 39000000.0),
    innerRadii: new Cesium.Cartesian3(3.0, 3.0, 3.0),
    minimumCone: Cesium.Math.toRadians(60.0),
    maximumCone: Cesium.Math.toRadians(140.0),
    material: Cesium.Color.DARKCYAN.withAlpha(0.3),
    outline: true,
  },
});

viewer.zoomTo(viewer.entities);
```
Call stack:
```
DeveloperError: All attribute lists must have the same number of attributes.

Error
    at new DeveloperError (https://sandcastle.cesium.com/CesiumUnminified/Workers/Check-40d84a28.js:64:13)
    at Geometry.computeNumberOfVertices (https://sandcastle.cesium.com/CesiumUnminified/Workers/GeometryAttribute-51d61732.js:326:17)
    at updateGeometryAfterSplit (https://sandcastle.cesium.com/CesiumUnminified/Workers/GeometryPipeline-576f16cd.js:2444:57)
    at updateInstanceAfterSplit (https://sandcastle.cesium.com/CesiumUnminified/Workers/GeometryPipeline-576f16cd.js:2489:20)
    at splitLongitudeTriangles (https://sandcastle.cesium.com/CesiumUnminified/Workers/GeometryPipeline-576f16cd.js:3042:5)
    at GeometryPipeline.splitLongitude (https://sandcastle.cesium.com/CesiumUnminified/Workers/GeometryPipeline-576f16cd.js:3703:9)
    at geometryPipeline (https://sandcastle.cesium.com/CesiumUnminified/Workers/PrimitivePipeline-27f11d3f.js:261:45)
    at PrimitivePipeline.combineGeometry (https://sandcastle.cesium.com/CesiumUnminified/Workers/PrimitivePipeline-27f11d3f.js:458:20)
    at combineGeometry (https://sandcastle.cesium.com/CesiumUnminified/Workers/combineGeometry.js:32:57)
    at callAndWrap (https://sandcastle.cesium.com/CesiumUnminified/Workers/createTaskProcessorWorker.js:63:25)
```
I initially reported this error on the [community pages](https://community.cesium.com/t/error-all-attribute-lists-must-have-the-same-number-of-attributes/21177).

**Comment by ggetz** [comment]
Thanks for the report @stewienj! I can reproduce on Chrome on MacOS as well. We'll need to look further into this to figure out exactly the edge case with that number of `slicePartitions`.

**Comment by philpil** [comment]
I have the same problem, getting "DeveloperError: All attribute list must have the same number of attributes.
Error 
at new US (blob:https://dev etc etc)
at Sh.computeNumberOfVertices (blob:https://dev etc etc)
at Vb (blob:https://dev etc etc)
at qh (blob:https://dev etc etc)
at kb (blob:https://dev etc etc)
at Lo.splitLongitude (blob:https://dev etc etc)
at cM (blob:https://dev etc etc)
at Ni (blob:https://dev etc etc)
at Ni.combineGeometry (blob:https://dev etc etc)
at _M (blob:https://dev etc etc)
at e (blob:https://dev etc etc) "

**Comment by c3-sxc** [comment]
I am also encountering this issue

**Comment by philpil** [comment]
@ggetz can we have an update on when this issue can be addressed?
