### ISSUE TITLE
use cesium 1.99 in project build error

### ISSUE THREAD

**Issue by super3s1988** [CesiumGS/cesium#10923]
i use cesium 1.99 in my angular project ,when i build my project by command "ng build --prod --output-hashing all --base-href /cesium-client",it report error ERROR in scripts.e83ba01e46c6e8f7646a.js from Terser Unexpected token: punc (.)

but i change cesium version to 1.83,it can build fine

ERROR in scripts.e83ba01e46c6e8f7646a.js from Terser
Unexpected token: punc (.) [scripts.e83ba01e46c6e8f7646a.js:3998,1531]
    at ee (D:\work\code\main-code\jt-client\node_modules\terser\dist\bundle.min.js:1:19541)
    at c (D:\work\code\main-code\jt-client\node_modules\terser\dist\bundle.min.js:1:28031)
    at l (D:\work\code\main-code\jt-client\node_modules\terser\dist\bundle.min.js:1:28122)
    at f (D:\work\code\main-code\jt-client\node_modules\terser\dist\bundle.min.js:1:28175)
    at G (D:\work\code\main-code\jt-client\node_modules\terser\dist\bundle.min.js:1:41989)
    at ge (D:\work\code\main-code\jt-client\node_modules\terser\dist\bundle.min.js:1:48275)
    at D:\work\code\main-code\jt-client\node_modules\terser\dist\bundle.min.js:1:49155
    at be (D:\work\code\main-code\jt-client\node_modules\terser\dist\bundle.min.js:1:49170)
    at ze (D:\work\code\main-code\jt-client\node_modules\terser\dist\bundle.min.js:1:50424)
    at qe (D:\work\code\main-code\jt-client\node_modules\terser\dist\bundle.min.js:1:50656)

**Comment by ggetz** [comment]
Hi, I believe this is the same issue which was described in https://github.com/CesiumGS/cesium/issues/10900. You can adjust your webpack configuration to avoid it as described in https://github.com/CesiumGS/cesium/issues/10900#issuecomment-1317076642.

I'll close this issue, but if you notice this is a sperate issue please feel free to reopen this.
