### ISSUE TITLE
npm run test on my mac: TOTAL: 3 FAILED, 13852 SUCCESS

### ISSUE THREAD

**Issue by rudifa** [CesiumGS/cesium#11139]
When I run `npm run test` on my mac, on the current `cesium` `main` branch (e.g. `50e612b44e`, or any other recent commit), typically I get the following 3 errors (sometimes only 2, sometimes up to 5 similar errors).

My mac is an Intel 4 cores, 2017, 16 GB RAM, 1TB SSD, 660MB available;  no other major activity at the time of tests.

- 3 errors, typical:
```
Chrome 110.0.0.0 (Mac OS 10.15.7): Executed 13855 of 13923 (3 FAILED) (skipped 68) (3 mins 3.458 secs / 2 mins 45.897 secs)
TOTAL: 3 FAILED, 13852 SUCCESS


1) 2D
     Scene/GeometryRenderingSpec SimplePolylineGeometry
     Expected not to render [0,0,0,255], but actually rendered [0,0,0,255].
    at <Jasmine>
    at render2D (packages/engine/Specs/Scene/GeometryRenderingSpec.js:159:21 <- Build/Specs/SpecList.js:87726:22)
    at UserContext.<anonymous> (packages/engine/Specs/Scene/GeometryRenderingSpec.js:1788:11 <- Build/Specs/SpecList.js:89200:11)
    at <Jasmine>

2) night vision
     Scene/PostProcessStageLibrary
     Expected 0 to be greater than 0.
    at <Jasmine>
    at packages/engine/Specs/Scene/PostProcessStageLibrarySpec.js:197:33 <- Build/Specs/SpecList.js:137099:33
    at compare (Specs/addDefaultMatchers.js:251:13 <- Build/Specs/karma-main.js:250:13)
    at <Jasmine>

3) renders pnts with point size style
     Scene/Model/Model3DTileContent pnts
     Expected not to render [0,0,0,255], but actually rendered [0,0,0,255].
    at <Jasmine>
    at packages/engine/Specs/Scene/Model/Model3DTileContentSpec.js:806:33 <- Build/Specs/SpecList.js:246632:33


TOTAL: 3 FAILED, 13852 SUCCESS
```
- 5 errors, details ommitted:
```
Chrome 110.0.0.0 (Mac OS 10.15.7): Executed 13854 of 13922 (5 FAILED) (skipped 68) (3 mins 7.488 secs / 2 mins 48.182 secs)
TOTAL: 5 FAILED, 13849 SUCCESS
1) 2D
     Scene/GeometryRenderingSpec SimplePolylineGeometry
2) renders
     Scene/ParticleSystem
3) night vision
     Scene/PostProcessStageLibrary
4) renders pnts with point size style
     Scene/Model/Model3DTileContent pnts
5) renders model with double-sided material
     Scene/Model/Model
TOTAL: 5 FAILED, 13849 SUCCESS
[16:18:47] Finished 'test' after 3.45 min
```

I am reporting this, as suggested by  @ggetz.

**Comment by okrayum** [comment]
This failure in the same spec happens on my machine, `npm run test` in Git locally,

<pre>
Chrome 128.0.0.0 (Windows 10):
2) renders pnts with style and normals
   Scene/Model/Model3DTileContent pnts
   Expected 1 to be 0.
   at &lt;Jasmine&gt;
   at packages/engine/Specs/Scene/Model/Model3DTileContentSpec.js:919:29 <- Build/Specs/SpecList.js:253629:29
   at compare (Specs/addDefaultMatchers.js:314:13 <- Build/Specs/karma-main.js:296:13)
   at &lt;Jasmine&gt;
   Expected 1 to be 0.
   at &lt;Jasmine&gt;
   at packages/engine/Specs/Scene/Model/Model3DTileContentSpec.js:920:29 <- Build/Specs/SpecList.js:253630:29
   at compare (Specs/addDefaultMatchers.js:314:13 <- Build/Specs/karma-main.js:296:13)
   at &lt;Jasmine&gt;
</pre>
