### ISSUE TITLE
Crash during rendering of point cloud with batch table

### ISSUE THREAD

**Issue by runaas** [CesiumGS/cesium#11166]
Cesium crashes in rendering of a point cloud file with batch table. If I use a .pnts file generated from the same data without point attributes (and no batch_table) it works without problems. The tileset has been testet with the 3d-tiles-validator without problems, and there are no issues during loading.

Cesium 1.96 didn't crash, but I was unable to extract point attributes, so something was not fully corrct. All versions from v 1.98 crashes (I've not tested 1.97...)

In the Unminified build of v 1.103 the crash happens here because of an undefined feature table:

BatchTexturePipelineStage.process@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:88762:26
ModelSceneGraph.prototype.buildDrawCommands@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:93454:32
buildDrawCommands@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:96083:23
Model.prototype.update@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:95960:20
Model3DTileContent.prototype.update@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:96812:9
Cesium3DTile.prototype.process@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:114825:17
processTiles@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:117608:14
Cesium3DTileset.prototype.prePassesUpdate@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:117498:15
PrimitiveCollection.prototype.prePassesUpdate@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:134434:17
prePassesUpdate@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:209512:14
tryAndCatchError@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:209585:22
Scene4.prototype.render@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:209624:19
CesiumWidget.prototype.render@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:210969:17
render2@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:210412:18
FrameRequestCallback*render2@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:210413:32
FrameRequestCallback*render2@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:210413:32
FrameRequestCallback*render2@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:210413:32
FrameRequestCallback*render2@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:210413:32
FrameRequestCallback*render2@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:210413:32
FrameRequestCallback*render2@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:210413:32
FrameRequestCallback*render2@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:210413:32
FrameRequestCallback*startRenderLoop@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:210436:24
set@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:210808:26
CesiumWidget@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:210616:33
Viewer@http://norgei3d.no/Cesium/Current/Build/CesiumUnminified/index.js:244618:24

Example that should crash almost immediately:
http://norgei3d.no/Cesium/Current/Apps/HelloBug.html

Browser:
Tested on Firefox, Chrome and Edge

Operating System:
Only tested on Windows

I'm really not sure if there is something wrong with my .pnts implementation or with Cesium, but if the error is mine it should still give an error message in the validator, and the  Cesium crash should rather happen in the file loading process than in rendering.

I have tried to track down the bug, but debugging in the 200k+ line unminified js is not easy and the data path from loading to rendering is rather convoluted...

**Comment by jjhembd** [comment]
I can reproduce the bug. Here is the message I get:

```bash
Error: Cannot read properties of undefined (reading 'featuresLength')
TypeError: Cannot read properties of undefined (reading 'featuresLength')
    at BatchTexturePipelineStage.process (http://localhost:8080/Build/CesiumUnminified/index.js:100096:39)
    at ModelSceneGraph.buildRenderResources (http://localhost:8080/Build/CesiumUnminified/index.js:115184:32)
    at ModelSceneGraph.buildDrawCommands (http://localhost:8080/Build/CesiumUnminified/index.js:115139:37)
    at buildDrawCommands (http://localhost:8080/Build/CesiumUnminified/index.js:118710:23)
    at Model.update (http://localhost:8080/Build/CesiumUnminified/index.js:118533:3)
    at Model3DTileContent.update (http://localhost:8080/Build/CesiumUnminified/index.js:119536:9)
    at Cesium3DTile.process (http://localhost:8080/Build/CesiumUnminified/index.js:136329:19)
    at processTiles (http://localhost:8080/Build/CesiumUnminified/index.js:140241:12)
    at Cesium3DTileset.prePassesUpdate (http://localhost:8080/Build/CesiumUnminified/index.js:140100:3)
    at PrimitiveCollection.prePassesUpdate (http://localhost:8080/Build/CesiumUnminified/index.js:157485:17)
```

I suspect something is happening in `PntsParser`. For this problematic dataset, I'm seeing these keys on the `parsedContent`:
```bash
Object.keys(parsedContent): draco,hasPositions,hasColors,isTranslucent,hasNormals,hasBatchIds,rtcCenter,pointsLength,positions,normals,colors,hasConstantColor,batchIds,batchLength
```
Note the absence of a `batchTableJson`.

For the "PointCloudBatched" dataset in the [3D Tiles Formats Sandcastle](https://sandcastle.cesium.com/?src=3D%20Tiles%20Formats.html), the keys are as follows:
```bash
Object.keys(parsedContent): draco,hasPositions,hasColors,isTranslucent,hasNormals,hasBatchIds,rtcCenter,pointsLength,positions,normals,colors,hasConstantColor,batchIds,batchLength,batchTableJson,batchTableBinary
```
A `batchTableJson` is included, as it (presumably) should be in both cases.

**Comment by javagl** [comment]
I was curious whether the validator might have missed something here. But I  don't think so. 

As already noted by jjhembd , the root cause is the missing batch table information. This, in turn, is caused by the line  https://github.com/CesiumGS/cesium/blob/553ac5760205fa6c4de4cd3a28d887fda566a565/packages/engine/Source/Scene/PntsParser.js#L178 which does not insert any batch table information into the `parsedContent` _at all_ when there is no batch table _binary_. In the given example there is no batch table binary. But there still is a valid batch table: All batch table information is stored directly in JSON (and the length of the binary part is 0).

Changing the line to 
`if (defined(batchTableBinary) || defined(batchTableJson)) {`
looks like a "quick patch", but things have to be investigated/tested more thoroughly. E.g. there later is another dubious check at https://github.com/CesiumGS/cesium/blob/553ac5760205fa6c4de4cd3a28d887fda566a565/packages/engine/Source/Scene/Model/PntsLoader.js#L558 - it's not clear whether this code path should be taken when the `batchTableBinary` is _defined_, but has a length of 0. (It seems to "work", but has to be tested/reviewed more  thoroughly...)

**Comment by jjhembd** [comment]
@javagl thanks for the insight. The fix "seems" relatively simple, and it would be nice to close this out. Do you want to open your proposed change as a PR? I can help with review & testing if needed.

**Comment by javagl** [comment]
I'll note that as a TODO. The downstream paths may require some further review (e.g. the role of that `hasDracoBatchTable` and whatnot), but a baseline fix+validation _should_ be simple.

**Comment by javagl** [comment]
I'm not sure whether I should insert a brittle "quick fix" for the PNTS case, or review the code and check whether up to 6 places require the same "quick fix", or whether I should start a small refactoring to make the world a better place. Fow now, I opened https://github.com/CesiumGS/cesium/issues/12805
