### ISSUE TITLE
CloudCollection 创建成功之后，调用销毁（destroy）方法报错！

### ISSUE THREAD

**Issue by Southjor** [CesiumGS/cesium#11175]
Sandcastle example: [CloudCollection example](https://sandcastle.cesium.com/#c=pVVbb9owFP4rRzwlGzUhNO3KaLWVadKkbqvaqnvhxSQHsOrYyHZoWdX/Pl8SoCuoVAWB4uNz+75zSS6FNrBgeI8KTkHgPQxRs6okt14WjVq5Pw+lMJQJVKNWGx5HAsCgUlZyqeSCFaj6jWGukBr8IxUvboJKFLedARMTeS4f+jChXKMX6ZmsePFVsNKa9MGoysmf4s8jMRK5z03nKNCmFnIk/uivO7s/7hKGPg/IuawK/Yr6SNTJ/6RmRjSaKyoKWf6qyjGqa8QiSknmsppUIjdMCpg+1/kh7GmKUcnELeUWBZT0wT/FgS2FplICIvcM0KjBR9gMLPDhmdcohg8QNZ7gYGUXOzcun6c1UQHo8yIOnWwoOUefdRSI9RySuWIlM2yBmtCiiIJ5XFNr0xcV5XwJc6mZR1z7ZwLMDKGUlW8IvcFJqPw5ze8u6BKVD66jmoBg7kM9BhLGik1nRqDW/YR020HYhFu105AqY5+o6JGJkuU3nCpEHR1005QcnSSf2nCYkcOTozb0kiSuveiccttPm0w0btKolyVJG7JspW0JZmVVXrO/O2x6UWYtupn99VYhOMutekJ6XuB7FmA70jeBOk49pKzbhvRoP0Rp4hBt4N8XUepQvUB0eLIB6b1okizAsaHSbE84x75A3TfD6W0tULpGE0rkvnZwdrRrMwHfbfMbCZdSGW5nshmbnJaoKJnw5Y0MjBSoDRN0/67Nug0njhX7H1KWiqGdqeCn5nqGtGBi2n+2Joy8slIqnL91+ebM5LPdimmjp+w6cLQkgZb1vr22KHOqDUdX7Rsp+Ziq88oYuzhGLYdSySUw494Aq5lfjbfdQdJacjmtVwlh+luwseszDuNR39S+olq4h2md4utpKizlAt+X5Yv9GJxurMg3JN1qtwbaLDmeBfoBvrBybpsKKsUjQjoGyzm3jag74yq/Q0NyXccAGHQ2TQcFWwArTre8ky2zVGt7M6k4d3Myap0NOlb/hSmXvqN+L1BxunRqs+7ZRRASQgYde9xuaQLV/3n+Bw)

Browser: Google Chrome : 版本 110.0.5481.177（正式版本） （64 位）

Operating System: windows 10

---

使用 `const clouds = new Cesium.CloudCollection();  `

创建云层，可以正常显示，但是调用` CloudCollection 的 destroy `方法，确提示错误如下：

```
An error occurred while rendering.  Rendering has stopped.
DeveloperError: This object was destroyed, i.e., destroy() was called.
Error
    at new DeveloperError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:10435:13)
    at CloudCollection.throwOnDestroyed (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:27496:13)
    at PrimitiveCollection.update (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:155359:21)
    at updateAndRenderPrimitives (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:227514:23)
    at executeCommandsInViewport (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:227366:5)
    at Scene4.updateAndExecuteCommands (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:227184:7)
    at render (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:227822:11)
    at tryAndCatchError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:227836:7)
    at Scene4.render (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:227888:7)
    at CesiumWidget.render (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:234123:19)
```

但是使用` scene.primitives.remove(clouds); `可以删除成功！

**Comment by Southjor** [comment]
使用 remove 是没问题的；但是 destroy 不是 CloudCollection 的方法属性吗，我想销毁这个对象，调用它本身的方法为什么会提示错误呢？还是说 destroy 会销毁其他所有的 primitive 对象？
