### ISSUE TITLE
glTF rendering error

### ISSUE THREAD

**Issue by chun8933** [CesiumGS/cesium#11280]
Before we are using CesiumJS 1.93 and it works, after upgraded to 1.105 it fails, error show in below:

RuntimeError: Fragment shader failed to compile.  Compile log: WARNING: 0:2: 'GL_OES_standard_derivatives' : extension is not supported
ERROR: 0:326: 'v_texCoord_0' : undeclared identifier
ERROR: 0:326: '=' : dimension mismatch
ERROR: 0:326: '=' : cannot convert from 'const highp float' to 'highp 2-component vector of float'

Error
    at new RuntimeError (http://localhost:8080/Build/CesiumUnminified/index.js:15434:11)
    at createAndLinkProgram (http://localhost:8080/Build/CesiumUnminified/index.js:36538:9)
    at reinitialize (http://localhost:8080/Build/CesiumUnminified/index.js:36691:19)
    at initialize2 (http://localhost:8080/Build/CesiumUnminified/index.js:36686:3)
    at ShaderProgram._bind (http://localhost:8080/Build/CesiumUnminified/index.js:36745:3)
    at beginDraw (http://localhost:8080/Build/CesiumUnminified/index.js:182260:17)
    at Context.draw (http://localhost:8080/Build/CesiumUnminified/index.js:182346:3)
    at DrawCommand.execute (http://localhost:8080/Build/CesiumUnminified/index.js:33512:11)
    at executeCommand (http://localhost:8080/Build/CesiumUnminified/index.js:231039:52)
    at executeCommands2 (http://localhost:8080/Build/CesiumUnminified/index.js:231345:7)

    I have tried the latest gltf-pipeline to remove the unsupported extension, but still no hope ...

    Extensions of the model which working in 1.93: (named a.gltf)
    "CESIUM_RTC",
    "WEB3D_quantized_attributes",
    "KHR_techniques_webgl"

    Extensions of the model after gltf-pipeline: (named b.gltf)
    "CESIUM_RTC",
    "WEB3D_quantized_attributes"
   
    both a and b glTF having the same error when import to 1.105, and only a.gltf in 1.93 is working.
    
    can anyone please help?

**Comment by chun8933** [comment]
> Hi @chun8933, Are you using a Custom Shader?
> 
> Can you share a Sandcastle link that replicates the issue? Here is how to do it:
> 
> 1. Go to https://sandcastle.cesium.com/
> 2. Edit the "JavaScript code" tab with your JavaScript code
> 3. Edit the "HTML body & CSS" tab (if needed)
> 4. Click on the "Share" button and copy the provided URL
> 
> Thanks!

Dear @jjhembd,

Thx for the reply

Sorry i am new to the project, dont really know does Custom shader is using or not, but after having tests with different version of Cesium, seems 1.9x are all working, can i say that no Custom Sader is used? as i just pass the model url to every cesium version and without any code dependence work.

I have uploaded 2 gltf files to the drive, and embeded them to sandcastle, same script is working in my local env but not in the public cesium env... sorry for that, still share the link with you and hope you will spend time to have a look.

On the other hand, please let me know what can i do for easily problem tracking and solving.

Requested link:
https://sandcastle.cesium.com/#c=xVXbbtw2EP2VgZ7kQKZ2vXbSbNdGbSdACtStG7vtQ1UElDRaEqFIlaT20sD/3qEu3kvcl7x0gcWu5nLmnJkhlaacLZWv4BSE942bp2lp5QpZIbjUHgtR4ooVpk4LZdoyvf3w289pSBjyMp2mjwLBWLmUmivowNbGfnawll5AgU62NazQOmk0TNnbTQJ560EbDzIYppMN22Q6IOXfyCV/5nJdebRg0SG3hUjAIdYOvECLwOmLG4+6YxLqu7ZpjPVYBiYUBBrXz1RNNZAPuM6AhMJocvq0bZaWl9hlHApvndTL7u9pIxtUUiPEe6AnwHUJgq/65JF3qHBDPXFeKkXMQJgGGaC1xkKNzvElghNm7UaiRMUZRTE13+Y9WGNNrrAG6Ui/4kGVN5BFf7y/mb379HfLtZf/YPmJe28lTQBdFoXC9wq5QxComo5dzfWWADfBB69eDWzRBUC+pEkkXblhb6hamHaQ3c07DDgIynSg6GElcU0Tuexae9v1k/3e2eIs6vt7a7QnWLRZlMCXTAOJrMyN2cyh4sphEkwOFRaeWvijLmXBvbEHXsFL6s4cvG1Hi2lVea1lTZ3o7Zl+Ovk+MKta3UFBYZG8d6ZEFbdWJdQEuRT+pGfRU2dIffMSHbNYmxVeKxX3MAC9xMY42cFdjgJvOS2Vk1zPWGVN/Q6XFtHFIQXgdHo2Y5M35+evp2+T3nR+ziYXk9mbyevB0PMI/0OpsZBAXoZGP9e5414wbz6SmWsXT2cX++GN9IWg4MmezRpasEOTaI7G86Evcx/SP1J8PNRNesSkA9kvRGeAmsQPe/BoiVJlbO2YOAL8taWuW03hQ0vGDo7qGztK3xXpxrAl/OOx8LKMvxzizI8R9xjO9x8Gdx02YA4DCkBr5RzCQoyGWtIitfW93KB6oFM0h+nZdzsv3wTvQ8EVec4m9Bl8T93vU9+sgbi3vPiM5ftRTy+MIp52p8Y0gZ0j758hcyDm6faa04kert5oFKf7w0EHYlzs+GQnZn/JRxsQyrfd91Gyw7ggoWwyPvcinzUnLxDP/w/i+dfEpxf/zTvTf3V790B3YcGdp0uWNuzRGJVze4e6jYfhhLwoiRbObxVejWg/yDq8UsL2xIylHusm3MUuzVuaumeFc2PBRbqfuijlCmR5+cKtCIXizpGnalW3fll0tUgp/qtUZbqT9gu9bhTfhjAxvfqpNzLGFik9vpzpe4FHyP8C

Many Thx!
Chun.

**Comment by ggetz** [comment]
@jjhembd Is this related to https://github.com/CesiumGS/cesium/pull/11308 at all?

**Comment by jjhembd** [comment]
Thanks for the update @chun8933! The Sandcastle is failing because of CORS errors, but I downloaded your file locally and was able to reproduce the bug.

@ggetz #11308 will take care of the first "WARNING":

```
WARNING: 0:2: 'GL_OES_standard_derivatives' : extension is not supported
```

But the real error here is the next line:

```
ERROR: 0:326: 'v_texCoord_0' : undeclared identifier
```

This is a bug in `MaterialPipelineStage`. The `processTexture` function adds the define `#define TEXCOORD_BASE_COLOR v_texCoord_0` but does not verify that `v_texCoord_0` was ever declared.

As a quick hack, I tried adding a `ShaderBuilder.addVarying` call to `processTexture`. This fixes the above error, but then there is another error:

```
RuntimeError: Fragment shader failed to compile.  Compile log: ERROR: 0:241: '=' : dimension mismatch
ERROR: 0:241: 'assign' : cannot convert from 'highp 2-component vector of float' to 'highp 3-component vector of float'
ERROR: 0:15: 'return' : function return is not matching type:
```

These errors are all because `v_normalEC` is declared as a `vec2`, when we were expecting a `vec3`.

@chun8933 is there any chance the glTF can be re-generated with 3-component normals?

**Comment by chun8933** [comment]
Ths for the reply @jjhembd, tbh, i have no idea to re-generate the glTF with 3-componet normals, as the model has been passed to us for few years ago, cant reach the vendor out now...
As told with the team, the model should be a 2D mesh model, i think that why it has only vec2 for the normal and do not have the 3rd axises.
but, is there any ways for me the manual fix the issue? or any suggestions? 
many thx..

**Comment by javagl** [comment]
The glTF contains an extension, namely, `WEB3D_quantized_attributes`, which is actually a glTF 1.0 extension, and it's not really widely supported. 

Beyond that, it contains some inconsistencies in the input - for example, it appears to be missing texture coordinates. It _could_ be possible to salvage some of the data. This would involve decoding the quantized attributes (probably with OCT-encoded normals) in a manual process. There almost certainly is no tool that can do this out-of-the-box. But it might be doable, with a ~"a few" hours of implementation work. But even then, it may be difficult to handle the remaining inconsistencies...

Here is a version of the file with the `WEB3D_quantized_attributes` extension being removed:

[cesiumIssue11280.zip](https://github.com/CesiumGS/cesium/files/12284743/cesiumIssue11280.zip)

This **STILL** contains errors, because there is no obvious way of how to fix the missing texture coordinates (and the normals are not decoded yet). It can be rendered in https://gltf-viewer.donmccurdy.com/ ...

![Cesium Issue 11280](https://github.com/CesiumGS/cesium/assets/5597569/0fe4feae-8559-4381-9361-a4b10ff9c572)

... but polishing it in a way so that it passes validation and can be rendered in every viewer may require more work...

**Comment by LoongZP** [comment]
According to @jjhembd 's answer, there are actually two errors here. One is "'v_texCoord_0': undeclared identifier" and the other is "cannot convert from 'highp 2-component vector of float' to 'highp 3-component vector of float'". Is there a solution to the second error, please? If you can, please give a detailed workaround for the first error by the way.Thank you.

**Comment by javagl** [comment]
This is connected to https://github.com/CesiumGS/cesium/issues/10821 

Some context: CesiumJS internally uses `gltf-pipeline` to upgrade glTF 1.0 to glTF 2.0. This does not necessarily upgrade the oct-encoded ("2-component") normals that are causing the issue here. There is some functionality for upgrading this sort of data in the 3D Tiles Tools (around https://github.com/CesiumGS/3d-tiles-tools/pull/98 ). This functionality is currently _not_ available as a "standalone" command-line function. But depending on the context, it should be possible to salvage the data here.

For example, @LoongZP : In which context do you receive this message? Is this as part of a B3DM file that contains old data? (If it is a whole tileset with old B3DM files, then you could try the `upgrade --targetVersion 1.1` functionality of the 3D Tiles Tools...)
