### ISSUE TITLE
Replace karma

### ISSUE THREAD

**Issue by ggetz** [CesiumGS/cesium#11295]
We use karma for running our jasmine unit tests via the command line, particularly for CI. Recently, [karma has been deprecated](https://github.com/karma-runner/karma#karma-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes). 

We'll need to find a replacement workflow. Karma's docs suggest:

> Both [Web Test Runner](https://modern-web.dev/docs/test-runner/overview/) and [jasmine-browser-runner](https://github.com/jasmine/jasmine-browser-runner) provide browser-based unit testing solutions which can be used as a direct alternative. [Jest](https://jestjs.io/) and [Vitest](https://vitest.dev/) also provide Node-based alternatives.

**Comment by jiangheng90** [comment]
Recently I have tried use vitest run cesium 3dtiles unit test via web browser mode and got stuck in createScene

**Comment by ggetz** [comment]
Starting to see some deprecation warnings related to karma...

```
16 09 2025 09:46:21.978:WARN [web-server]: 404: /images/Cesium_Logo_Color.jpg
(node:62954) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
    at common.setupOutgoing (/Users/gabby/workspace/cesium/node_modules/http-proxy/lib/http-proxy/common.js:43:22)
    at Array.stream (/Users/gabby/workspace/cesium/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:127:14)
    at ProxyServer.<anonymous> (/Users/gabby/workspace/cesium/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
    at createProxy (/Users/gabby/workspace/cesium/node_modules/karma/lib/middleware/proxy.js:96:25)
    at call (/Users/gabby/workspace/cesium/node_modules/connect/index.js:239:7)
    at next (/Users/gabby/workspace/cesium/node_modules/connect/index.js:183:5)
    at /Users/gabby/workspace/cesium/node_modules/karma/lib/middleware/source_files.js:55:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

**Comment by ggetz** [comment]
This is becoming more immanent. 

[`jasmine-core@6.0.0` officially deprecated karma support](https://github.com/jasmine/jasmine/blob/main/release_notes/6.0.0.md), with plans to drop support entirely in 7.0.

Updating to `jasmine-core@6.0.0` [will require compatibility updates for use with karma](https://jasmine.github.io/upgrade-guides/6.0#if-you-use-jasmine-browser-runner) that we may not get the chance to make before the next release. But we may want to do this update more intentionally as a step in the process of replacing karma entirely.

**Comment by jjhembd** [comment]
More deprecation warnings, now related to karma dependencies, when I run `npm install`:

```bash
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Old versions of glob are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me
```
