### ISSUE TITLE
Cesium stops rendering cesium 1.108

### ISSUE THREAD

**Issue by saadatali48** [CesiumGS/cesium#11445]
Getting this error
"
Cesium.js:22364 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading ‘_target’)
at UniformSampler.set (Cesium.js:22364:23)
at ShaderProgram._setUniforms (Cesium.js:23287:19)
at continueDraw (Cesium.js:36008:19)
at Context.draw (Cesium.js:36072:5)
at DrawCommand.execute (Cesium.js:20250:13)
at executeCommand (Cesium.js:221224:17)
at executeCommands2 (Cesium.js:221474:11)
at executeCommandsInViewport (Cesium.js:221938:5)
at Scene4.updateAndExecuteCommands (Cesium.js:221745:7)
at Picking.pick (Cesium.js:211209:11)
at Scene4.pick (Cesium.js:222473:26)
at _callee6$ (Pools.tsx:2193:1)
at tryCatch (runtime.js:63:1)
at Generator.invoke [as _invoke] (runtime.js:293:1)
at Generator.next (runtime.js:118:1)
at asyncGeneratorStep (asyncToGenerator.js:3:1)
at _next (asyncToGenerator.js:25:1)
at asyncToGenerator.js:32:1
at new Promise ()
at asyncToGenerator.js:21:1
at onMouseMove (Pools.tsx:2179:1)
at handleMouseMove (Cesium.js:178115:7)
at handlePointerMove (Cesium.js:178504:7)
at HTMLCanvasElement.listener (Cesium.js:177861:7)
"

I have implemented clipping on google photorealistic tiles. The problem is, when I clip an area, and then on mouse hover on 3D model / extruded polygon within clipped area, viewer gets crashed… I don't know why is this happening because with cesium 1.91 everything is working fine.

![Capture](https://github.com/CesiumGS/cesium/assets/56907536/58bd49be-9876-44a2-b76c-c2f6199d6edd)

**Comment by saadatali48** [comment]
Hi @ggetz, 

I am having the same issue as reported in [#11410](https://github.com/CesiumGS/cesium/issues/11410) , 
My implementation a bit different in terms of adding clipping planes. I have multiple options in the UI, and user can select to clip any of the part of 3D tilesets (bind to the UI using a polygon). 
But the problem is, when I switch from 1 clipping area to another, and as soon as I zoom in or out the viewer throws above error.

**Comment by ggetz** [comment]
Got it, thanks @saadatali48. I'll close this issue to keep the discussion in #11410.
