### ISSUE TITLE
Chinese Mainland cannot request https://dev.virtualearth.net/REST/v1/Imagery/Metadata/Aerial? service

### ISSUE THREAD

**Issue by freefer** [CesiumGS/cesium#11532]
RuntimeError: An error occurred while accessing https://dev.virtualearth.net/REST/v1/Imagery/Metadata/Aerial?jsonp=loadJsonp421197&incl=ImageryProviders&key=AmXdbd8UeUJtaRSn7yVwyXgQlBBUqliLbHpgn2c76DfuHwAXfRrgS5qwfHU6Rhm8&uriScheme=http
Error
    at new RuntimeError (http://localhost:8010/Build/CesiumUnminified/index.js:11520:11)
    at metadataFailure3 (http://localhost:8010/Build/CesiumUnminified/index.js:185185:9)
    at requestMetadata4 (http://localhost:8010/Build/CesiumUnminified/index.js:185198:5)
    at async BingMapsImageryProvider.fromUrl (http://localhost:8010/Build/CesiumUnminified/index.js:185442:3)
    at async IonImageryProvider.fromAssetId (http://localhost:8010/Build/CesiumUnminified/index.js:188775:23)
    at async handlePromise (http://localhost:8010/Build/CesiumUnminified/index.js:189843:16)

![image](https://github.com/CesiumGS/cesium/assets/9861446/cbade750-1417-4fd6-8583-a7accb52c01f)

**Comment by ggetz** [comment]
Hi there. I'm not sure this is a bug with CesiumJS. 

The default imagery layer points to [Bing Maps](https://www.microsoft.com/en-us/maps), which has their own policies around data use.

You can replace the deault imagery with any other imagery layer. See our [Imagery Layer Tutorial](https://cesium.com/learn/cesiumjs-learn/cesiumjs-imagery/) for more info. Thanks!
