### ISSUE TITLE
Cesium.js Dependency Installation Failure

### ISSUE THREAD

**Issue by srarlight** [CesiumGS/cesium#11572]
I encountered an error while attempting to install the dependencies of Cesium.js. The error message is as follows: 

 Error: ENOENT: no such file or directory, copyfile 'node_modules/draco3d/draco_decoder.wasm' -> 'packages/engine/Source/ThirdParty/draco_decoder.wasm'
    at copyFileSync (node:fs:2969:3)
    at prepare (file:///C:/Users/yiwenjian.ETOP/Documents/project/cesium-main/gulpfile.js:365:3)
    at taskWrapper (C:\Users\yiwenjian.ETOP\Documents\project\cesium-main\node_modules\.pnpm\r2.cnpmjs.org+undertaker@1.3.0\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (node:domain:433:15)
    at runBound (node:domain:444:12)
    at asyncRunner (C:\Users\yiwenjian.ETOP\Documents\project\cesium-main\node_modules\.pnpm\r2.cnpmjs.org+async-done@1.3.2\node_modules\async-done\index.js:55:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
 ELIFECYCLE  Command failed with exit code 1.

The version of Node.js I am using is 18.17.1, and the version of pnpm is 8.9.2.

I would appreciate any assistance or insights into this issue. Thank you.

**Comment by ggetz** [comment]
Hi there,

Thanks for the report. 

Based on the pnpm docs, [you may need to run with an `-r` flag to install all necessary dependencies](https://pnpm.io/pnpm-vs-npm#directory-dependencies).

**Comment by ggetz** [comment]
!
