### ISSUE TITLE
Error constructing CesiumWidget on Chrome Version 119.0.6045.159 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by jdromero88** [CesiumGS/cesium#11636]
I found this issue that might be related, but it is from 2016 #4442 
on the site https://get.webgl.org/ it says my browser supports webgl so I'm not sure why im getting the error.
![image](https://github.com/CesiumGS/cesium/assets/51330062/e7f94a9d-8c4d-4037-97d0-7bbfc0bb241a)

```
Visit http://get.webgl.org/ to verify that your web browser and hardware support WebGL.  Consider trying a different web browser or updating your video drivers.  Detailed error information is below:

RuntimeError: The browser supports WebGL, but initialization failed.
Error
    at new RuntimeError (https://unpkg.com/cesium@1.84.0/Build/Cesium/Cesium.js:1:40928)
    at new Context (https://unpkg.com/cesium@1.84.0/Build/Cesium/Cesium.js:1:2564308)
    at new Scene (https://unpkg.com/cesium@1.84.0/Build/Cesium/Cesium.js:1:3257162)
    at new CesiumWidget (https://unpkg.com/cesium@1.84.0/Build/Cesium/Cesium.js:1:3543218)
    at new Viewer (https://unpkg.com/cesium@1.84.0/Build/Cesium/Cesium.js:1:3633785)
    at f.init (https://satellitedashboard.org/_nuxt/8db18c4.js:2:1005581)
    at https://satellitedashboard.org/_nuxt/8db18c4.js:2:1014016
    at M (https://satellitedashboard.org/_nuxt/8db18c4.js:2:1855148)
    at Generator._invoke (https://satellitedashboard.org/_nuxt/8db18c4.js:2:1854901)
    at Generator.next (https://satellitedashboard.org/_nuxt/8db18c4.js:2:1855475)
```
![image](https://github.com/CesiumGS/cesium/assets/51330062/76a02701-5b7b-4ca0-94a6-59085a4dff61)

System info:
```bash
  Kernel: 6.5.0-1007-oem x86_64 bits: 64 compiler: N/A
  Desktop: Cinnamon 5.8.4 tk: GTK 3.24.33 wm: muffin dm: LightDM 1.30.0
  Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
```

**Comment by ggetz** [comment]
Thanks for the report @jdromero88.

Could you please visit webglreport.com and take a screenshot of your results for both the WebGL 1 and WebGL 2 tabs?

**Comment by jdromero88** [comment]
Hi @ggetz here are the screenshots:
WebGL 1:
![image](https://github.com/CesiumGS/cesium/assets/51330062/8227148d-2ff2-43ea-ac4c-5fa769eae21c)
WebGL 2:
![image](https://github.com/CesiumGS/cesium/assets/51330062/e7ef1c47-c394-4a5a-979d-03512faf629a)
the list continues here
```

WebGL 2 Functions Implementation Status:
	

88 of 88 new functions implemented.
	copyBufferSubData
	getBufferSubData
	blitFramebuffer
	framebufferTextureLayer
	getInternalformatParameter
	invalidateFramebuffer
	invalidateSubFramebuffer
	readBuffer
	renderbufferStorageMultisample
	texStorage2D
	texStorage3D
	texImage3D
	texSubImage3D
	copyTexSubImage3D
	compressedTexImage3D
	compressedTexSubImage3D
	getFragDataLocation
	uniform1ui
	uniform2ui
	uniform3ui
	uniform4ui
	uniform1uiv
	uniform2uiv
	uniform3uiv
	uniform4uiv
	uniformMatrix2x3fv
	uniformMatrix3x2fv
	uniformMatrix2x4fv
	uniformMatrix4x2fv
	uniformMatrix3x4fv
	uniformMatrix4x3fv
	vertexAttribI4i
	vertexAttribI4iv
	vertexAttribI4ui
	vertexAttribI4uiv
	vertexAttribIPointer
	vertexAttribDivisor
	drawArraysInstanced
	drawElementsInstanced
	drawRangeElements
	drawBuffers
	clearBufferiv
	clearBufferuiv
	clearBufferfv
	clearBufferfi
	createQuery
	deleteQuery
	isQuery
	beginQuery
	endQuery
	getQuery
	getQueryParameter
	createSampler
	deleteSampler
	isSampler
	bindSampler
	samplerParameteri
	samplerParameterf
	getSamplerParameter
	fenceSync
	isSync
	deleteSync
	clientWaitSync
	waitSync
	getSyncParameter
	createTransformFeedback
	deleteTransformFeedback
	isTransformFeedback
	bindTransformFeedback
	beginTransformFeedback
	endTransformFeedback
	transformFeedbackVaryings
	getTransformFeedbackVarying
	pauseTransformFeedback
	resumeTransformFeedback
	bindBufferBase
	bindBufferRange
	getIndexedParameter
	getUniformIndices
	getActiveUniforms
	getUniformBlockIndex
	getActiveUniformBlockParameter
	getActiveUniformBlockName
	uniformBlockBinding
	createVertexArray
	deleteVertexArray
	isVertexArray
	bindVertexArray
```

**Comment by ggetz** [comment]
Thanks @jdromero88. 

1. Does [constructing the viewer with a WebGL1 context](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md#1102---2023-02-01) work for you?
1. Do any [other WebGL](https://www.khronos.org/webgl/wiki/Demo_Repository) applications have a similar problem, or are you only seeing it with Cesium?

**Comment by ggetz** [comment]
@jdromero88 I'm closing this issue due to inactivity. If you believe this is still an issue, please feel free to re-open. Thanks!

**Comment by ismailsunni** [comment]
Hello @ggetz 
I have the same issue as the following:
![image](https://github.com/CesiumGS/cesium/assets/1421861/98c5be70-b67b-40d8-b33e-fe60c5476248)

My code is more or less:
```
  this.viewer = new Viewer(div, {
      animation: false,
      fullscreenButton: false,
      homeButton: false,
      infoBox: true,
      sceneModePicker: false,
      selectionIndicator: false,
      timeline: false,
      globe: true,
    })
```

If I didn't set the globe to true, it wouldn't give me the issue.

I also tried with 
```
      contextOptions: {
        requestWebgl1: true,
      },
```
but the issue still remains

https://get.webgl.org/ says that my browser supports webGL

> Does [constructing the viewer with a WebGL1 context](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md#1102---2023-02-01) work for you?

Still not working


> Do any [other WebGL](https://www.khronos.org/webgl/wiki/Demo_Repository) applications have a similar problem, or are you only seeing it with Cesium?

Others are fine, I only see the problem on my cesium.

webglreport:
![image](https://github.com/CesiumGS/cesium/assets/1421861/290f8319-efb9-49d7-a4ca-0081ca03b75b)

![image](https://github.com/CesiumGS/cesium/assets/1421861/1e0af206-74bf-4d67-89ad-750ebd7f5720)

**Comment by ismailsunni** [comment]
@ggetz Yes, the div is valid. 
As I mentioned when I remove the globe option, it works fine. The error said that it was related to WebGL. Do you have a reason why this doesn't have to do with WebGL?

Thanks
