### ISSUE TITLE
Local spec failures when testing against a release

### ISSUE THREAD

**Issue by jjhembd** [CesiumGS/cesium#11666]
I get the following errors when testing against the release with `npm run test -- --failTaskOnError --release`:

```bash
Chrome 119.0.0.0 (Windows 10): Executed 13953 of 14021 (skipped 68) SUCCESS (2 mins 46.355 secs / 2 mins 31.914 secs)
Chrome 119.0.0.0 (Windows 10): Executed 12334 of 14021 (8 FAILED) (skipped 64) (0 secs / 1 min 33.741 secs)
TOTAL: 8 FAILED, 26279 SUCCESS


1) Syncs time when looping
     Core/VideoSynchronizer
     Error: Timeout - function did not complete within 5000ms
    at poller (Specs/pollToPromise.js:26:11 <- Build/Specs/SpecList.js:3278:11)

2) Syncs time when not looping
     Core/VideoSynchronizer
     Error: Timeout - function did not complete within 5000ms
    at poller (Specs/pollToPromise.js:26:11 <- Build/Specs/SpecList.js:3278:11)

3) pickPosition
     Scene/Scene
     TypeError: Failed to execute 'shaderSource' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLShader'.
    at GLe (Build/Cesium/Cesium.js:884:65692)
    at Xq (Build/Cesium/Cesium.js:887:1409)
    at zA (Build/Cesium/Cesium.js:887:1361)
    at ep._bind (Build/Cesium/Cesium.js:887:2210)
    at b$e (Build/Cesium/Cesium.js:8328:41437)
    at Ld.draw (Build/Cesium/Cesium.js:8328:42272)
    at QL.execute (Build/Cesium/Cesium.js:884:36492)
    at If.executeCopyColor (Build/Cesium/Cesium.js:11452:5318)
    at Yi.resolveFramebuffers (Build/Cesium/Cesium.js:12496:34610)
    at Zht (Build/Cesium/Cesium.js:12496:37463)

4) pickPosition in CV
     Scene/Scene
     TypeError: Failed to execute 'shaderSource' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLShader'.
    at GLe (Build/Cesium/Cesium.js:884:65692)
    at Xq (Build/Cesium/Cesium.js:887:1409)
    at zA (Build/Cesium/Cesium.js:887:1361)
    at ep._bind (Build/Cesium/Cesium.js:887:2210)
    at b$e (Build/Cesium/Cesium.js:8328:41437)
    at Ld.draw (Build/Cesium/Cesium.js:8328:42272)
    at QL.execute (Build/Cesium/Cesium.js:884:36492)
    at If.executeCopyColor (Build/Cesium/Cesium.js:11452:5318)
    at Yi.resolveFramebuffers (Build/Cesium/Cesium.js:12496:34610)
    at Zht (Build/Cesium/Cesium.js:12496:37463)

5) pickPosition in 2D
     Scene/Scene
     RangeError: Invalid array length
    at ylt (Build/Cesium/Cesium.js:11703:9176)
    at wk.createPotentiallyVisibleSet (Build/Cesium/Cesium.js:11703:11474)
    at sg (Build/Cesium/Cesium.js:12496:28470)
    at yht (Build/Cesium/Cesium.js:12496:28015)
    at Yi.updateAndExecuteCommands (Build/Cesium/Cesium.js:12496:25759)
    at Zht (Build/Cesium/Cesium.js:12496:37431)
    at TT (Build/Cesium/Cesium.js:12496:37629)
    at Yi.render (Build/Cesium/Cesium.js:12496:38622)
    at renderAndReadPixels (Specs/addDefaultMatchers.js:736:11 <- Build/Specs/karma-main.js:612:11)
    at compare (Specs/addDefaultMatchers.js:307:30 <- Build/Specs/karma-main.js:292:30)

6) pickPosition returns undefined when useDepthPicking is false
     Scene/Scene
     RangeError: Invalid array length
    at ylt (Build/Cesium/Cesium.js:11703:9176)
    at wk.createPotentiallyVisibleSet (Build/Cesium/Cesium.js:11703:11474)
    at sg (Build/Cesium/Cesium.js:12496:28470)
    at Yi.updateAndExecuteCommands (Build/Cesium/Cesium.js:12496:25729)
    at Zht (Build/Cesium/Cesium.js:12496:37431)
    at TT (Build/Cesium/Cesium.js:12496:37629)
    at Yi.render (Build/Cesium/Cesium.js:12496:38622)
    at renderAndReadPixels (Specs/addDefaultMatchers.js:736:11 <- Build/Specs/karma-main.js:612:11)
    at compare (Specs/addDefaultMatchers.js:307:30 <- Build/Specs/karma-main.js:292:30)
    at <Jasmine>

7) pickPosition picks translucent geometry when pickTranslucentDepth is true
     Scene/Scene
     RangeError: Invalid array length
    at ylt (Build/Cesium/Cesium.js:11703:9176)
    at wk.createPotentiallyVisibleSet (Build/Cesium/Cesium.js:11703:11474)
    at sg (Build/Cesium/Cesium.js:12496:28470)
    at Yi.updateAndExecuteCommands (Build/Cesium/Cesium.js:12496:25729)
    at Zht (Build/Cesium/Cesium.js:12496:37431)
    at TT (Build/Cesium/Cesium.js:12496:37629)
    at Yi.render (Build/Cesium/Cesium.js:12496:38622)
    at renderAndReadPixels (Specs/addDefaultMatchers.js:736:11 <- Build/Specs/karma-main.js:612:11)
    at compare (Specs/addDefaultMatchers.js:307:30 <- Build/Specs/karma-main.js:292:30)
    at <Jasmine>

8) pickPosition caches results per frame
     Scene/Scene
     TypeError: Failed to execute 'shaderSource' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLShader'.
    at GLe (Build/Cesium/Cesium.js:884:65692)
    at Xq (Build/Cesium/Cesium.js:887:1409)
    at zA (Build/Cesium/Cesium.js:887:1361)
    at ep._bind (Build/Cesium/Cesium.js:887:2210)
    at b$e (Build/Cesium/Cesium.js:8328:41437)
    at Ld.draw (Build/Cesium/Cesium.js:8328:42272)
    at QL.execute (Build/Cesium/Cesium.js:884:36492)
    at If.executeCopyColor (Build/Cesium/Cesium.js:11452:5318)
    at Yi.resolveFramebuffers (Build/Cesium/Cesium.js:12496:34610)
    at Zht (Build/Cesium/Cesium.js:12496:37463)


TOTAL: 8 FAILED, 26279 SUCCESS
[11:12:17] 'test' errored after 2.93 min
[11:12:17] Error: 1
    at formatError (/home/jhembd/CesiumGS/cesium/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/home/jhembd/CesiumGS/cesium/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (node:events:525:35)
    at Gulp.emit (node:domain:489:12)
    at Object.error (/home/jhembd/CesiumGS/cesium/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/home/jhembd/CesiumGS/cesium/node_modules/now-and-later/lib/map.js:50:14)
    at f (/home/jhembd/CesiumGS/cesium/node_modules/once/once.js:25:25)
    at f (/home/jhembd/CesiumGS/cesium/node_modules/once/once.js:25:25)
    at tryCatch (/home/jhembd/CesiumGS/cesium/node_modules/async-done/index.js:24:15)
    at done (/home/jhembd/CesiumGS/cesium/node_modules/async-done/index.js:40:12)
```

This is only when testing locally against the release. A basic `npm test` runs through with no errors, and CI passes.

**Comment by ggetz** [comment]
I'm intermittently seeing the same failures for `Scene/Scene`. It's with a different error stack, though that could be due to release vs dev. I will post the error stack when I run into it again.

Potentially a race condition with another test?

**Comment by jjspace** [comment]
@ggetz are these the error stacks you were seeing? I'm getting them again for the same tests

```shell
Chrome 120.0.0.0 (Linux x86_64): Executed 107 of 14044 (6 FAILED) (skipped 13937) (8.259 secs / 6.773 secs)
TOTAL: 6 FAILED, 101 SUCCESS


1) pickPosition
     Scene/Scene
     DeveloperError: normalized result is not a number
error properties: undefined: undefined
    at new DeveloperError (packages/engine/Source/Core/DeveloperError.js:39:11 <- Build/CesiumUnminified/Cesium.js:10465:13)
    at Cartesian3.normalize (packages/engine/Source/Core/Cartesian3.js:450:11 <- Build/CesiumUnminified/Cesium.js:11123:13)
    at Ellipsoid.geodeticSurfaceNormal (packages/engine/Source/Core/Ellipsoid.js:379:21 <- Build/CesiumUnminified/Cesium.js:18832:31)
    at Object.resultat [as eastNorthUpToFixedFrame] (packages/engine/Source/Core/Transforms.js:200:19 <- Build/CesiumUnminified/Cesium.js:28205:21)
    at setView3D (packages/engine/Source/Scene/Camera.js:1240:37 <- Build/CesiumUnminified/Cesium.js:201383:47)
    at Camera.setView (packages/engine/Source/Scene/Camera.js:1493:5 <- Build/CesiumUnminified/Cesium.js:201551:7)
    at UserContext.<anonymous> (packages/engine/Specs/Scene/SceneSpec.js:890:20 <- Build/Specs/SpecList.js:215291:21)
    at <Jasmine>

2) pickPosition in CV
     Scene/Scene
     DeveloperError: normalized result is not a number
error properties: undefined: undefined
    at new DeveloperError (packages/engine/Source/Core/DeveloperError.js:39:11 <- Build/CesiumUnminified/Cesium.js:10465:13)
    at Cartesian3.normalize (packages/engine/Source/Core/Cartesian3.js:450:11 <- Build/CesiumUnminified/Cesium.js:11123:13)
    at PerspectiveOffCenterFrustum.computeCullingVolume (packages/engine/Source/Core/PerspectiveOffCenterFrustum.js:253:14 <- Build/CesiumUnminified/Cesium.js:63045:24)
    at PerspectiveFrustum.computeCullingVolume (packages/engine/Source/Core/PerspectiveFrustum.js:312:33 <- Build/CesiumUnminified/Cesium.js:63357:35)
    at Scene4.updateFrameState (packages/engine/Source/Scene/Scene.js:1882:45 <- Build/CesiumUnminified/Cesium.js:218653:47)
    at render (packages/engine/Source/Scene/Scene.js:3729:9 <- Build/CesiumUnminified/Cesium.js:219954:11)
    at tryAndCatchError (packages/engine/Source/Scene/Scene.js:3797:5 <- Build/CesiumUnminified/Cesium.js:220007:7)
    at Scene4.render (packages/engine/Source/Scene/Scene.js:3887:5 <- Build/CesiumUnminified/Cesium.js:220059:7)
    at renderAndReadPixels (Specs/addDefaultMatchers.js:736:11 <- Build/Specs/karma-main.js:612:11)
    at compare (Specs/addDefaultMatchers.js:307:30 <- Build/Specs/karma-main.js:292:30)
     DeveloperError: normalized result is not a number
error properties: undefined: undefined
    at new DeveloperError (packages/engine/Source/Core/DeveloperError.js:39:11 <- Build/CesiumUnminified/Cesium.js:10465:13)
    at Cartesian3.normalize (packages/engine/Source/Core/Cartesian3.js:450:11 <- Build/CesiumUnminified/Cesium.js:11123:13)
    at Ellipsoid.geodeticSurfaceNormalCartographic (packages/engine/Source/Core/Ellipsoid.js:355:21 <- Build/CesiumUnminified/Cesium.js:18818:31)
    at Ellipsoid.cartographicToCartesian (packages/engine/Source/Core/Ellipsoid.js:401:8 <- Build/CesiumUnminified/Cesium.js:18839:10)
    at getColumbusViewTo3DCamera (packages/engine/Source/Scene/SceneTransitioner.js:381:13 <- Build/CesiumUnminified/Cesium.js:213488:15)
    at SceneTransitioner.morphTo3D (packages/engine/Source/Scene/SceneTransitioner.js:270:18 <- Build/CesiumUnminified/Cesium.js:213410:20)
    at Scene4.morphTo3D (packages/engine/Source/Scene/Scene.js:4412:22 <- Build/CesiumUnminified/Cesium.js:220216:24)
    at UserContext.<anonymous> (packages/engine/Specs/Scene/SceneSpec.js:86:13 <- Build/Specs/SpecList.js:214634:14)
    at <Jasmine>

3) pickPosition in 2D
     Scene/Scene
     DeveloperError: normalized result is not a number
error properties: undefined: undefined
    at new DeveloperError (packages/engine/Source/Core/DeveloperError.js:39:11 <- Build/CesiumUnminified/Cesium.js:10465:13)
    at Cartesian3.normalize (packages/engine/Source/Core/Cartesian3.js:450:11 <- Build/CesiumUnminified/Cesium.js:11123:13)
    at Ellipsoid.geodeticSurfaceNormal (packages/engine/Source/Core/Ellipsoid.js:379:21 <- Build/CesiumUnminified/Cesium.js:18832:31)
    at Ellipsoid.cartesianToCartographic (packages/engine/Source/Core/Ellipsoid.js:472:18 <- Build/CesiumUnminified/Cesium.js:18870:20)
    at updateMembers (packages/engine/Source/Scene/Camera.js:703:67 <- Build/CesiumUnminified/Cesium.js:200948:69)
    at Camera.get (packages/engine/Source/Scene/Camera.js:907:7 <- Build/CesiumUnminified/Cesium.js:201116:9)
    at updateCameraDeltas (packages/engine/Source/Scene/Camera.js:339:14 <- Build/CesiumUnminified/Cesium.js:200662:16)
    at Camera._updateCameraChanged (packages/engine/Source/Scene/Camera.js:375:3 <- Build/CesiumUnminified/Cesium.js:200684:5)
    at Scene4.initializeFrame (packages/engine/Source/Scene/Scene.js:3666:15 <- Build/CesiumUnminified/Cesium.js:219906:17)
    at renderAndReadPixels (Specs/addDefaultMatchers.js:735:11 <- Build/Specs/karma-main.js:611:11)

4) pickPosition returns undefined when useDepthPicking is false
     Scene/Scene
     DeveloperError: normalized result is not a number
error properties: undefined: undefined
    at new DeveloperError (packages/engine/Source/Core/DeveloperError.js:39:11 <- Build/CesiumUnminified/Cesium.js:10465:13)
    at Cartesian3.normalize (packages/engine/Source/Core/Cartesian3.js:450:11 <- Build/CesiumUnminified/Cesium.js:11123:13)
    at Ellipsoid.geodeticSurfaceNormal (packages/engine/Source/Core/Ellipsoid.js:379:21 <- Build/CesiumUnminified/Cesium.js:18832:31)
    at Ellipsoid.cartesianToCartographic (packages/engine/Source/Core/Ellipsoid.js:472:18 <- Build/CesiumUnminified/Cesium.js:18870:20)
    at updateMembers (packages/engine/Source/Scene/Camera.js:703:67 <- Build/CesiumUnminified/Cesium.js:200948:69)
    at Camera.get (packages/engine/Source/Scene/Camera.js:893:7 <- Build/CesiumUnminified/Cesium.js:201103:9)
    at getGlobeHeight (packages/engine/Source/Scene/Scene.js:3606:31 <- Build/CesiumUnminified/Cesium.js:219867:34)
    at Scene4.initializeFrame (packages/engine/Source/Scene/Scene.js:3656:23 <- Build/CesiumUnminified/Cesium.js:219898:25)
    at renderAndReadPixels (Specs/addDefaultMatchers.js:735:11 <- Build/Specs/karma-main.js:611:11)
    at compare (Specs/addDefaultMatchers.js:307:30 <- Build/Specs/karma-main.js:292:30)

5) pickPosition picks translucent geometry when pickTranslucentDepth is true
     Scene/Scene
     DeveloperError: normalized result is not a number
error properties: undefined: undefined
    at new DeveloperError (packages/engine/Source/Core/DeveloperError.js:39:11 <- Build/CesiumUnminified/Cesium.js:10465:13)
    at Cartesian3.normalize (packages/engine/Source/Core/Cartesian3.js:450:11 <- Build/CesiumUnminified/Cesium.js:11123:13)
    at Ellipsoid.geodeticSurfaceNormal (packages/engine/Source/Core/Ellipsoid.js:379:21 <- Build/CesiumUnminified/Cesium.js:18832:31)
    at Ellipsoid.cartesianToCartographic (packages/engine/Source/Core/Ellipsoid.js:472:18 <- Build/CesiumUnminified/Cesium.js:18870:20)
    at updateMembers (packages/engine/Source/Scene/Camera.js:703:67 <- Build/CesiumUnminified/Cesium.js:200948:69)
    at Camera.get (packages/engine/Source/Scene/Camera.js:893:7 <- Build/CesiumUnminified/Cesium.js:201103:9)
    at getGlobeHeight (packages/engine/Source/Scene/Scene.js:3606:31 <- Build/CesiumUnminified/Cesium.js:219867:34)
    at Scene4.initializeFrame (packages/engine/Source/Scene/Scene.js:3656:23 <- Build/CesiumUnminified/Cesium.js:219898:25)
    at renderAndReadPixels (Specs/addDefaultMatchers.js:735:11 <- Build/Specs/karma-main.js:611:11)
    at compare (Specs/addDefaultMatchers.js:307:30 <- Build/Specs/karma-main.js:292:30)

6) pickPosition caches results per frame
     Scene/Scene
     DeveloperError: normalized result is not a number
error properties: undefined: undefined
    at new DeveloperError (packages/engine/Source/Core/DeveloperError.js:39:11 <- Build/CesiumUnminified/Cesium.js:10465:13)
    at Cartesian3.normalize (packages/engine/Source/Core/Cartesian3.js:450:11 <- Build/CesiumUnminified/Cesium.js:11123:13)
    at Ellipsoid.geodeticSurfaceNormal (packages/engine/Source/Core/Ellipsoid.js:379:21 <- Build/CesiumUnminified/Cesium.js:18832:31)
    at Ellipsoid.cartesianToCartographic (packages/engine/Source/Core/Ellipsoid.js:472:18 <- Build/CesiumUnminified/Cesium.js:18870:20)
    at updateMembers (packages/engine/Source/Scene/Camera.js:703:67 <- Build/CesiumUnminified/Cesium.js:200948:69)
    at Camera.get (packages/engine/Source/Scene/Camera.js:893:7 <- Build/CesiumUnminified/Cesium.js:201103:9)
    at getGlobeHeight (packages/engine/Source/Scene/Scene.js:3606:31 <- Build/CesiumUnminified/Cesium.js:219867:34)
    at Scene4.initializeFrame (packages/engine/Source/Scene/Scene.js:3656:23 <- Build/CesiumUnminified/Cesium.js:219898:25)
    at renderAndReadPixels (Specs/addDefaultMatchers.js:735:11 <- Build/Specs/karma-main.js:611:11)
    at compare (Specs/addDefaultMatchers.js:307:30 <- Build/Specs/karma-main.js:292:30)


TOTAL: 6 FAILED, 101 SUCCESS

```

**Comment by ptrgags** [comment]
I also have had a local spec failure (that also failed in CI but only once). It also uses `npm run test --release` but with other options (e.g. headless Chrome). I opened https://github.com/CesiumGS/cesium/issues/11733 since the error was quite a bit different.

**Comment by ggetz** [comment]
@ptrgags Yes, this is a different error.

**Comment by jjhembd** [comment]
A few observations on these errors:

- Each failed spec passes if run individually as a focused test.
- When running the whole `SceneSpec` suite, several lost context warnings appear in the console: `WARNING: Too many active WebGL contexts. Oldest context will be lost.`
- The suite declares a global `scene` in `beforeAll`. Many of the specs, however, construct and destroy their own scene.
- The problematic specs are using the global `scene`, and fail _after_ a lost context warning.

I think the lost contexts are the problem. In `afterEach` we are updating the aspect ratio as follows:
```javascript
      camera.frustum.aspectRatio =
        scene.drawingBufferWidth / scene.drawingBufferHeight;
```

After a lost context, `scene.drawingBufferHeight === 0`, so `camera.frustum.aspectRatio === NaN`. This causes problems in the individual specs when they call `camera.setView`.
