### ISSUE TITLE
An error occurred while rendering. Rendering has stopped. []

### ISSUE THREAD

**Issue by slsanjith** [CesiumGS/cesium#11686]
TypeError: t[n].update is not a function

TypeError: t[n].update is not a function
    at qs.update (http://127.0.0.1:5500/v4.0.0/cesium/Cesium-1.112/Build/Cesium/Cesium.js:8318:110537)
    at Ege (http://127.0.0.1:5500/v4.0.0/cesium/Cesium-1.112/Build/Cesium/Cesium.js:12496:31675)
    at sg (http://127.0.0.1:5500/v4.0.0/cesium/Cesium-1.112/Build/Cesium/Cesium.js:12496:28461)
    at Yi.updateAndExecuteCommands (http://127.0.0.1:5500/v4.0.0/cesium/Cesium-1.112/Build/Cesium/Cesium.js:12496:25729)
    at Zht (http://127.0.0.1:5500/v4.0.0/cesium/Cesium-1.112/Build/Cesium/Cesium.js:12496:37431)
    at TT (http://127.0.0.1:5500/v4.0.0/cesium/Cesium-1.112/Build/Cesium/Cesium.js:12496:37629)
    at Yi.render (http://127.0.0.1:5500/v4.0.0/cesium/Cesium-1.112/Build/Cesium/Cesium.js:12496:38622)
    at ST.render (http://127.0.0.1:5500/v4.0.0/cesium/Cesium-1.112/Build/Cesium/Cesium.js:12498:1631)
    at n (http://127.0.0.1:5500/v4.0.0/cesium/Cesium-1.112/Build/Cesium/Cesium.js:12496:52908)
![image](https://github.com/CesiumGS/cesium/assets/12496024/8a07bca6-cec3-4385-aa70-6049dd22cc3d)

`viewer = new Cesium.Viewer("mapDiv", {
            terrain: Cesium.Terrain.fromWorldTerrain(),
        });

        setTimeout(() => {

            viewer.camera.flyTo({
                destination: Cesium.Cartesian3.fromDegrees(-74.019, 40.6912, 750),
                orientation: {
                    heading: Cesium.Math.toRadians(20),
                    pitch: Cesium.Math.toRadians(-20),
                },
                duration: 0,
            });

            const osmBuildingsTileset = Cesium.createOsmBuildingsAsync();
            viewer.scene.primitives.add(osmBuildingsTileset);

        }, 1000);`

**Comment by ggetz** [comment]
`Cesium.createOsmBuildingsAsync` returns a Promise, so `const osmBuildingsTileset = Cesium.createOsmBuildingsAsync();` should be `const osmBuildingsTileset = await Cesium.createOsmBuildingsAsync();`.
