### ISSUE TITLE
 The new version of Cesium fails to load the pnts model.

### ISSUE THREAD

**Issue by whuxxie** [CesiumGS/cesium#11735]
### What happened?

 I have an older version of code, and the Cesium version is 1.51. The display of pnts 3dtiles works normally, but when I switch to the latest version of Cesium, the following error occurs. How can I resolve this? Has the 3dtiles format changed?

CesiumWidget.js:727 An error occurred while rendering. Rendering has stopped.
TypeError: Cannot read properties of undefined (reading 'updateTransform')
TypeError: Cannot read properties of undefined (reading 'updateTransform')
    at Cesium3DTileset.get (http://127.0.0.1:5500/CesiumUnminified/Cesium.js:123404:20) 
    at updateZoomTarget (http://127.0.0.1:5500/CesiumUnminified/Cesium.js:250181:35) 
    at Viewer._postRender (http://127.0.0.1:5500/CesiumUnminified/Cesium.js:250129:5) 
    at Event.raiseEvent (http://127.0.0.1:5500/CesiumUnminified/Cesium.js:25800:22) 
    at Scene4.render (http://127.0.0.1:5500/CesiumUnminified/Cesium.js:220123:24) 
    at CesiumWidget.render (http://127.0.0.1:5500/CesiumUnminified/Cesium.js:221510:19) 
    at render2 (http://127.0.0.1:5500/CesiumUnminified/Cesium.js:220933:20)

### Reproduction steps

1. load pnts model
2. can't load
3.
...

### Environment

Browser:
CesiumJS Version: old 1.51  new 1.113
Operating System:windows 11

**Comment by ggetz** [comment]
Hi @whuxxie, there has been [many significant changes since 1.51](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md), including adding support for 3D Tiles 1.1 and refactoring existing 3D Tiles code.

We're going to need more info in order to determine the problem. Would you be able to provide the point cloud in question?

**Comment by ggetz** [comment]
I'm closing this issue due to inactivity. If you believe this is still an issue, please feel free to re-open. Thanks!

**Comment by whuxxie** [comment]
> I'm closing this issue due to inactivity. If you believe this is still an issue, please feel free to re-open. Thanks!

thank you，i solve this problem.

**Comment by LisaBiuBiu** [comment]
May I ask how the landlord solved it? I also encountered the same problem
