### ISSUE TITLE
Spec failure in GroundPolylinePrimitive

### ISSUE THREAD

**Issue by jjhembd** [CesiumGS/cesium#11807]
After updating terrain heights in https://github.com/CesiumGS/cesium/pull/11805, one spec in GroundPolylinePrimitive fails locally:

```bash
1) renders with distance display condition per instance attribute
     Scene/GroundPolylinePrimitive
     Expected (0, 4) to be undefined.
    at <Jasmine>
    at packages/engine/Specs/Scene/GroundPolylinePrimitiveSpec.js:761:58 <- Build/Specs/SpecList.js:175807:58
    at compare (Specs/addDefaultMatchers.js:314:13 <- Build/Specs/karma-main.js:296:13)
    at <Jasmine>
```

The relevant spec has been excluded for now, since the error is caused by a fragile test rather than broken functionality.
The expectations in the spec should be updated.

**Comment by okrayum** [comment]
Just a comment about a spec failure I had  in `GroundPolylinePrimitive`. This is on the main branch locally. However, it has a different expectation:

![Screenshot 2024-08-29 142943](https://github.com/user-attachments/assets/cc39dc6c-6cba-425e-b64c-4af446271231)

Chrome 128.0.0.0 (Windows 10):

<pre>
1) picking in 3D
   Scene/GroundPolylinePrimitive
   Expected 'depth rectangle' to equal 'polyline on terrain'.
   at &lt;Jasmine&gt;
   at packages/engine/Specs/Scene/GroundPolylinePrimitiveSpec.js:821:27 <- Build/Specs/SpecList.js:178937:27
   at compare (Specs/addDefaultMatchers.js:387:13 <- Build/Specs/karma-main.js:355:13)
   at &lt;Jasmine&gt;
</pre>
