### ISSUE TITLE
@cesium/engine and @cesium/widgets dependency definitions cause older versions to break when new versions are deployed to npm due to use of ^

### ISSUE THREAD

**Issue by DrEchoDoobarius** [CesiumGS/cesium#11834]
### What happened?

Because of the way the dependencies for @cesium/engine and @cesium/widgets are defined with a ^, older versions get out of sync and break.
For example cesium 1.113.0 specifies the following dependencies:
  "dependencies": {
    "@cesium/engine": "^6.2.0",
    "@cesium/widgets": "^4.4.0"
  },
With the release of version 1.114.0 and corresponding engine 7.0.0 and widgets 4.5.0 version 1.113.0 will now resolve 
"@cesium/engine": "^6.2.0", -> 6.2.0
"@cesium/widgets": "^4.4.0" -> 4.5
Since version 1.113.0 now will resolve widgets 4.5, the dependencies are no longer internally consistent because widgets 4.5 depends on engine 7.0.0. This will cause widgets 4.5 to pull it's own engine 7.0.0 internal dependency.
Cesium will launch fine this way but will break in subtle and non obvious ways where ever there is a type check because imported classes will come from engine 6.2.0, and widgets or it's internal engine see the 7.0.0 and different types.
Couple examples of thing's we've seen break are:
- Selection on the globe not working because a typecheck fail not recognizing the selected entity as an entity.
- Creating an entity with cesium colors eg Color.DARKGREY, and getting a developer error because a type check fails on the Color.DARKGREY.

Similar issues have occurred with previous versions since the widgets/engine split, like 1.112.0 when 1.113.0  was published. Depending on the actual versions involved it may not break, but there could be a situation where you could end up getting an entirely new unexpected version if engine and widgets both have only minor version number changes.

### Reproduction steps

1. Install fresh cesium 1.113.0
2. cesium/widgets 4.5 will be resolved and it will have an internal engine 7.0.0 dependency 
3. Create an entity and add it to the globe
4. Selection will not work.

### Environment

CesiumJS Version: 1.113.0

**Comment by DrEchoDoobarius** [comment]
I think the first option is best to give users of the library the most control over exactly what they're getting.

**Comment by mschiavone-mx** [comment]
I agree with @DrEchoDoobarius thoughts above.  I found this issue and reported it here:  
https://community.cesium.com/t/cesium-js-1-110-suddenly-not-working-internal-dependency-issues/27868
Sadly, it received no response, but hopefully posting here will get more support.  

The temporary resolution was to add an overrides section in package.json to force the versions of the questionable dependencies.  (Note that the versions below must be appropriate for the Cesium version - these can be found in the cesium package in node_modules.

`"overrides": {`
`    "cesium": {`
`      "@cesium/engine": "6.1.1",`
`      "@cesium/widgets": "4.3.1"`
`    }`
`  }`

It works, but needs to be updated everytime we update the Cesium version.

**Comment by ggetz** [comment]
Also reported in https://github.com/CesiumGS/cesium/issues/12035.

**Comment by RadotJar** [comment]
Still an issue that I ran into after the most recent release of @cesium/engine that must have happened overnight. Requiring devs to specify a "resolutions" or "overrides" field in order for cesium to be stable in their projects seems like a very high priority problem to address. It doesn't seem right that minor version updates to @cesium/engine should be able to break cesium builds.

**Comment by jjhembd** [comment]
Hi @RadotJar, thanks for the update. Can you clarify how your cesium build is broken? Do you have an error message you can share?

In the case described at the top of this issue (for v1.114), there was a major version change in `engine` which led to `widgets` and the top-level package pulling incompatible versions of `engine`.

In the latest release (v1.145), there were no major version changes -- see https://github.com/CesiumGS/cesium/commit/578bd5f3e9a967853da68ea53c75e342178ee75c. So I wouldn't expect any builds to break.

I hear your point that the caret versioning still means your build will change (it's not "stable"). I just didn't expect it to actually break.

**Comment by RadotJar** [comment]
Thank you for your reply @jjhembd , these are the errors I was seeing when building my project with webpack:

```
17.98 ERROR in ../node_modules/cesium/Source/Cesium.js 754:0-65
17.98 export '_shadersPolygonSignedDistanceFS' (reexported as '_shadersPolygonSignedDistanceFS') was not found in '@cesium/engine' (possible exports: AlphaMode, ...

...

17.98 ERROR in ../node_modules/cesium/Source/Cesium.js 1185:0-54
17.98 export '_shadersclipPolygons' (reexported as '_shadersclipPolygons') was not found in '@cesium/engine' (possible exports: AlphaMode, ...

...

17.98 ERROR in ../node_modules/cesium/Source/Cesium.js 1249:0-63
17.98 export '_shadersunpackClippingExtents' (reexported as '_shadersunpackClippingExtents') was not found in '@cesium/engine' (possible exports: AlphaMode, ...
```

I've truncated the full list of possible exports in the errors for brevity.

We are using cesium v1.142.0 which appears to be pulling in @cesium/engine v26.3.0 and @cesium/widgets v16.2.0

I was able to resolve the issue by pinning @cesium/engine at v26.0.0 and @cesium/widgets at v16.0.0. I can't be sure what versions we were running before, but I assume whatever versions came before @cesium/engine v26.3.0 and/or @cesium/widgets v16.2.0.

**Comment by jdfwarrior** [comment]
I ran into the same issue recently. I mentioned it [here](https://community.cesium.com/t/invalid-dependencies/47195)

I recently updated to Cesium 1.145.0 in a branch but noticed a regression in our application. I adjusted my project’s package.json to target 1.144.0 again, removed all node_modules, and re-ran npm install to ensure everything was clean. When I did, I was getting errors from Vite though because Cesium has @cesium/engine: "^26.2.0"which allows it to pull what it considers compatible versions, including minor and patch versions. In this instance, it was pulling 26.3.0 which throws the following errors.

✘ [ERROR] No matching export in “node_modules/@cesium/engine/index.js” for import “_shadersPolygonSignedDistanceFS”

node_modules/cesium/Source/Cesium.js:482:9:
  482 │ export { _shadersPolygonSignedDistanceFS } from '@cesium/engine';
      ╵          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
✘ [ERROR] No matching export in “node_modules/@cesium/engine/index.js” for import “_shadersclipPolygons”

node_modules/cesium/Source/Cesium.js:1204:9:
  1204 │ export { _shadersclipPolygons } from '@cesium/engine';
       ╵          ~~~~~~~~~~~~~~~~~~~~
✘ [ERROR] No matching export in “node_modules/@cesium/engine/index.js” for import “_shadersunpackClippingExtents”

node_modules/cesium/Source/Cesium.js:1268:9:
  1268 │ export { _shadersunpackClippingExtents } from '@cesium/engine';
       ╵          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dferguson/dev/raid/node_modules/esbuild/lib/main.js:1467
let error = new Error(text);
^

Error: Build failed with 3 errors:
node_modules/cesium/Source/Cesium.js:482:9: ERROR: No matching export in “node_modules/@cesium/engine/index.js” for import “_shadersPolygonSignedDistanceFS”
node_modules/cesium/Source/Cesium.js:1204:9: ERROR: No matching export in “node_modules/@cesium/engine/index.js” for import “_shadersclipPolygons”
node_modules/cesium/Source/Cesium.js:1268:9: ERROR: No matching export in “node_modules/@cesium/engine/index.js” for import “_shadersunpackClippingExtents”
at failureErrorWithLog (/Users/dferguson/dev/raid/node_modules/esbuild/lib/main.js:1467:15)
at /Users/dferguson/dev/raid/node_modules/esbuild/lib/main.js:926:25
at /Users/dferguson/dev/raid/node_modules/esbuild/lib/main.js:1345:9
at process.processTicksAndRejections (node:internal/process/task_queues:104:5) {
errors: [Getter/Setter],
warnings: [Getter/Setter]
}

We pinned a version for now to get past it but seems like those should either be a fixed version of converted to a `~` instead of a `^` to prevent minor versions from potentially breaking it.
