### ISSUE TITLE
Sandcastle demo error for VRTheWorldTerrainProvider

### ISSUE THREAD

**Issue by lukemckinstry** [CesiumGS/cesium#12242]
### What happened?

Error in the following sandcastle when VRTheWorldTerrainProvider is selected

https://sandcastle.cesium.com/?src=Terrain.html

#### Selected menu option:
```json
{
      text: "VRTheWorldTerrainProvider",
      onselect: function () {
        viewer.scene.setTerrain(
          new Cesium.Terrain(
            Cesium.VRTheWorldTerrainProvider.fromUrl(
              "http://www.vr-theworld.com/vr-theworld/tiles1.0.0/73/",
              {
                credit: "Terrain data courtesy VT MÄK",
              },
            ),
          ),
        );
      },
    },
```

#### Error:
```
RuntimeError: An error occurred while accessing http://www.vr-theworld.com/vr-theworld/tiles1.0.0/73/
Error
    at new RuntimeError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:15023:13)
    at metadataFailure (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:189397:11)
    at requestMetadata2 (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:189404:7)
    at async VRTheWorldTerrainProvider.fromUrl (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:189508:5)
    at async handlePromise2 (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:241350:18)
```

### Reproduction steps

1.
2.
3.
...

### Environment

Browser: Chrome Version 128.0.6613.137 (Official Build) (64-bit)
CesiumJS Version: 1.122
Operating System: Ubuntu 22.04

**Comment by ggetz** [comment]
Thanks for writing this up @lukemckinstry.

 I believe we're already tracking it in https://github.com/CesiumGS/cesium/issues/6587. I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.
