### ISSUE TITLE
`VRTheWorldTerrainProvider` fails to retrieve terrain

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium#12329]
### What happened?

In the [Terrain](https://sandcastle.cesium.com/?src=Terrain.html) sandcastle I was mousing through options and selected "VRTheWorldTerrainProvider". Unfortunately, the terrain never loads; this runtime error prints instead:

```
RuntimeError: An error occurred while accessing http://www.vr-theworld.com/vr-theworld/tiles1.0.0/73/
Error
    at new RuntimeError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:15028:13)
    at metadataFailure (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:190514:11)
    at requestMetadata2 (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:190521:7)
    at async VRTheWorldTerrainProvider.fromUrl (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:190625:5)
    at async handlePromise2 (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:242351:18)
```

### Reproduction steps

1. Visit https://sandcastle.cesium.com/?src=Terrain.html
2. Select "VRTheWorldTerrainProvider".

![image](https://github.com/user-attachments/assets/50356369-60db-456f-83cf-9f92e0c2db9f)

![image](https://github.com/user-attachments/assets/6a4740c6-79b4-47d3-b61a-a330c6d51483)

### Sandcastle example

https://sandcastle.cesium.com/?src=Terrain.html

### Environment

Browser: Google Chrome
CesiumJS Version: 1.123
Operating System: Windows 11

**Comment by j9liu** [comment]
Whoops, duplicate of https://github.com/CesiumGS/cesium/issues/12030.
