### ISSUE TITLE
Invalid array length exception in Sandcastle Geometry and Appearances Example

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#2317]
- Open the Geometry and Appearances Sandcastle example
- Zoom in and look to the horizon.
- Grab the bottom/left of the sky atmosphere and use left-mouse drag to spin around 360 degrees and then look around.

![image](https://cloud.githubusercontent.com/assets/782098/5382924/4ebe8e32-807b-11e4-8553-825b22fbc841.png)

CC #1477

**Comment by hpinkos** [comment]
@pjcozzi I can't reproduce this

**Comment by mramato** [comment]
Someone else recently reported this on the forum, so it's definitely still happening.  Here's [the link](https://groups.google.com/d/msg/cesium-dev/xjaZc8xV4kA/t91pjoXBCAAJ).  They are on a Mac as well, so this could be platform specific.

**Comment by kainino0x** [comment]
I just accidentally reproduced this while zooming around aimlessly in Hello World. I'm on Chrome on Windows. Here's a trace with updated line numbers, too:

```
An error occurred while rendering.  Rendering has stopped.
undefined
RangeError: Invalid array length
RangeError: Invalid array length
    at updateFrustums (http://localhost:8090/Source/Scene/Scene.js:1037:36)
    at createPotentiallyVisibleSet (http://localhost:8090/Source/Scene/Scene.js:1202:13)
    at render (http://localhost:8090/Source/Scene/Scene.js:1806:9)
    at Scene.render (http://localhost:8090/Source/Scene/Scene.js:1845:13)
    at CesiumWidget.render (http://localhost:8090/Source/Widgets/CesiumWidget/CesiumWidget.js:659:25)
    at render (http://localhost:8090/Source/Widgets/CesiumWidget/CesiumWidget.js:68:32)
```
