### ISSUE TITLE
Cesium throws an exception if accessor.min and max are missing for POSITION

### ISSUE THREAD

**Issue by lasalvavida** [CesiumGS/cesium#3925]
In glTF, accessor.min and accessor.max are [optional properties](https://github.com/KhronosGroup/glTF/tree/master/specification#accessor).

If a model is missing these on an accessor that defines POSITION, Cesium throws:

DeveloperError: array is required
Error
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:44:19)
    at Function.Cartesian3.unpack (http://localhost:8080/Source/Core/Cartesian3.js:174:19)
    at computeBoundingSphere (http://localhost:8080/Source/Scene/Model.js:1080:55)
    at Model.update (http://localhost:8080/Source/Scene/Model.js:3286:36)
    at PrimitiveCollection.update (http://localhost:8080/Source/Scene/PrimitiveCollection.js:366:27)
    at updatePrimitives (http://localhost:8080/Source/Scene/Scene.js:1859:27)
    at executeCommandsInViewport (http://localhost:8080/Source/Scene/Scene.js:1817:9)
    at updateAndExecuteCommands (http://localhost:8080/Source/Scene/Scene.js:1716:17)
    at render (http://localhost:8080/Source/Scene/Scene.js:2052:9)
    at Scene.render (http://localhost:8080/Source/Scene/Scene.js:2090:13)

**Comment by pjcozzi** [comment]
Good catch, thanks @lasalvavida.  I am tempted to update the glTF 1.0.1 spec to say that min and max are required when the accessor is referenced from a `POSITION` (or require them always); otherwise, any implementation that uses bounding volumes (which is likely all non-trivial ones) has to have a fallback to explicitly compute it.  I opened https://github.com/KhronosGroup/glTF/issues/593 to discuss.

**Comment by pjcozzi** [comment]
The 1.0.1 spec will require accessor min and max.  Leaving this open until the online converter supports this.
