### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by vla9isla8** [CesiumGS/cesium#7842]
Sandcastle example: none

Browser: Chrome

Operating System: Windows 10

Cesium: 1.57.0

Resium: 1.4.1

I use react and resium for dynamically change entities. This error throws while changing entities set for display. Not every time!

I tried use **allowDataSourcesToSuspendAnimation=true** for Viewer, but error still exist.

Error log:

```index.js:1446 An error occurred while rendering.  Rendering has stopped.
undefined
TypeError: Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at regenerateShaders (http://localhost:3000/cesium/Cesium.js:154587:49)
    at Model.update (http://localhost:3000/cesium/Cesium.js:154452:17)
    at PrimitiveCollection.update (http://localhost:3000/cesium/Cesium.js:135088:27)
    at updateAndRenderPrimitives (http://localhost:3000/cesium/Cesium.js:241784:27)
    at executeCommandsInViewport (http://localhost:3000/cesium/Cesium.js:241623:13)
    at updateAndExecuteCommands (http://localhost:3000/cesium/Cesium.js:241431:13)
    at render (http://localhost:3000/cesium/Cesium.js:242082:9)
    at tryAndCatchError (http://localhost:3000/cesium/Cesium.js:242102:13)
    at Scene.render (http://localhost:3000/cesium/Cesium.js:242170:13)
    at CesiumWidget.render (http://localhost:3000/cesium/Cesium.js:253644:25)
    at render (http://localhost:3000/cesium/Cesium.js:253025:32)
```

**Comment by OmarShehata** [comment]
Please try to put together a code example to help us reproduce this. If this does not happen when using just CesiumJS I would assume it's an issue in the Resium library. 

Having the stack trace from the unminified version of Cesium would also help to see where the error is coming from.

**Comment by vla9isla8** [comment]
@OmarShehata another exception view 
```
index.js:1446 An error occurred while rendering.  Rendering has stopped.
undefined
TypeError: Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at regenerateShaders (http://localhost:3000/static/js/2.chunk.js:177110:43)
    at Model.push../node_modules/cesium/Source/Scene/Model.js.Model.update (http://localhost:3000/static/js/2.chunk.js:176977:9)
    at PrimitiveCollection.push../node_modules/cesium/Source/Scene/PrimitiveCollection.js.PrimitiveCollection.update (http://localhost:3000/static/js/2.chunk.js:195974:21)
    at updateAndRenderPrimitives (http://localhost:3000/static/js/2.chunk.js:201562:23)
    at executeCommandsInViewport (http://localhost:3000/static/js/2.chunk.js:201398:7)
    at updateAndExecuteCommands (http://localhost:3000/static/js/2.chunk.js:201248:7)
    at render (http://localhost:3000/static/js/2.chunk.js:201852:5)
    at tryAndCatchError (http://localhost:3000/static/js/2.chunk.js:201871:7)
    at Scene.push../node_modules/cesium/Source/Scene/Scene.js.Scene.render (http://localhost:3000/static/js/2.chunk.js:201926:7)
    at CesiumWidget.push../node_modules/cesium/Source/Widgets/CesiumWidget/CesiumWidget.js.CesiumWidget.render (http://localhost:3000/static/js/2.chunk.js:262869:19)
    at render (http://localhost:3000/static/js/2.chunk.js:262231:20)
```
I have throuble to shot mapped stack trace :/
Anyway, it happens at **node_modules/cesium/Source/Scene/Model.js#4773**

```
// Fix all the commands, marking them as dirty so everything that derives will re-derive
        var rendererPrograms = rendererResources.programs;

        var nodeCommands = model._nodeCommands;
        var commandCount = nodeCommands.length;
        for (var i = 0; i < commandCount; ++i) {
            var nodeCommand = nodeCommands[i];
            programId = nodeCommand.programId;

  ->      var renderProgram = rendererPrograms[programId];
            nodeCommand.command.shaderProgram = renderProgram;
            if (defined(nodeCommand.command2D)) {
                nodeCommand.command2D.shaderProgram = renderProgram;
            }
}        
```
Maybe should check **rendererPrograms** before access to members?

**Comment by OmarShehata** [comment]
@vla9isla8 thanks for finding the line of code where this exception is thrown. It does sound like it's hitting an unexpected scenario here. 

Can you show the code in your application for changing the entities? This error only happens when you have dynamic entities, right?

**Comment by vla9isla8** [comment]
@OmarShehata As you can see at stack trace, i dont know where is the problem and can't send you code for all application. For display models used entity with model grathics, like `
entity = {
...,
model: {
url: {path_to_gltf}
}
}
` , and entity with poligon. Exception raised after changing camera position(flyTo), model highlight (silhouetteColor) and poligon closeTop and material props, some of those. 

Btw, i tried change Model.js code and add check cachedRendererResources.programs before use it.
```
if (isClippingEnabled(model) || isColorShadingEnabled(model) || model._shouldRegenerateShaders || !cachedRendererResources.programs) {
            model._shouldRegenerateShaders = false;

            rendererResources.programs = {};
            rendererResources.silhouettePrograms = {};

            var visitedPrograms = {};
            var techniques = model._sourceTechniques;
            var technique;

            for (var techniqueId in techniques) {
                if (techniques.hasOwnProperty(techniqueId)) {
                    technique = techniques[techniqueId];
                    programId = technique.program;
                    if (!visitedPrograms[programId]) {
                        visitedPrograms[programId] = true;
                        recreateProgram({
                            programId: programId,
                            techniqueId: techniqueId
                        }, model, frameState.context);
                    }
                }
            }
        } else {
            rendererResources.programs = cachedRendererResources.programs;
            rendererResources.silhouettePrograms = cachedRendererResources.silhouettePrograms;
        }
```
And it works fine :)

**Comment by vla9isla8** [comment]
@OmarShehata rendering entities with resium.
```
<Entity
                show={!!model && !!position && show}
                orientation={orientation}
                position={toCartesianPosition(position)}
                onClick={this.onClick}>
        {model && model.uri && <ModelGraphics
                    {...model}
                    uri={model.uri}
                    runAnimations={inMotion}
                    color={selected ? TrackableComponent.highlightColor : null}
                    colorBlendMode={selected ? ColorBlendMode.MIX : ColorBlendMode.HIGHLIGHT}
                    colorBlendAmount={0.2}
                    silhouetteColor={TrackableComponent.silhouetteColor}
                    silhouetteSize={selected ? 3 : 0} />}
</Entity>
```
```
<Entity
                id={`zone_${id}`}
                onClick={this.onClick} >
        <PolygonGraphics
                    fill
                    hierarchy={hierarchy}
                    closeTop={!selected}
                    closeBottom={true}
                    height={height + altitude}
                    heightReference={HeightReference.RELATIVE_TO_GROUND}
                    extrudedHeight={altitude}
                    extrudedHeightReference={HeightReference.RELATIVE_TO_GROUND}
                    material={material}
                    outline={false}
                    show={show}
                />
</Entity>
```
All entities are inside Viewer compoment.

**Comment by OmarShehata** [comment]
It's difficult to pinpoint exactly where the issue is caused from with the provided examples @vla9isla8. Can you see if this error happens when using entities in the same way on Sandcastle (https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/) ?

**Comment by lilleyse** [comment]
@vla9isla8 I've been looking at the `Model` code trying to figure out why `cachedRendererResources` would not be ready before shaders are regenerated. My theory right now is that the model shaders get regenerated before textures are loaded, because only when textures are loaded does `cachedRendererResources` get set.

On your model entities could you try setting `incrementallyLoadTextures` to `false`? This will help narrow it down.

**Comment by ggetz** [comment]
Closing this issue due to lack of activity.
