### ISSUE TITLE
Camera crashes when flying underground

### ISSUE THREAD

**Issue by Joyzen** [CesiumGS/cesium#8226]
Sandcastle example: 

https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=ZU9Nb4MwDP0rEZdSCYWi3hitpnXHSTt02ikXNxiIFhzkBKqu6n9fSjtpH77Yz37v2Z6AxWTwiCw2gvAodujN2Mv3uZcu9Ax3jgIYQl4sHxQpuimkhh4ZZGNPb+7JjVQbavdDh4zpWZGIoZECcnk33QGHWAGtZcOuf8aWEX1aFEW2Xi8zhtqMvlwpumRn1zQeQ3n36RCu5uUqG0zQXcwM1OLMvSwVJVlS+XCyuL3xH00/OA5iZJtKmQfsBwtxd34Y9QcGqb2/flLl36KqNpMw9UYlfz5WidAWvI+TZrR2bz5RJdsqj/xfMuvmC18nZAunK6Urti+3ppSyyiP8rwrO2QPwD8cv

Browser: Chrome 77.0.3865.90    64bit

Operating System: Windows10 

you need to drag cesium-container to wider such as 1606*645 and run then when camera flied to the target position the viewer crushed!!!

Only accured when the frustum'aspectRatio being bigger.

```
TypeError: Cannot read property 'southwest' of undefined
TypeError: Cannot read property 'southwest' of undefined
    at visitVisibleChildrenNearToFar (https://cesiumjs.org/Cesium/Source/Scene/QuadtreePrimitive.js:902:44)
    at visitTile (https://cesiumjs.org/Cesium/Source/Scene/QuadtreePrimitive.js:813:13)
    at visitIfVisible (https://cesiumjs.org/Cesium/Source/Scene/QuadtreePrimitive.js:946:20)
    at visitVisibleChildrenNearToFar (https://cesiumjs.org/Cesium/Source/Scene/QuadtreePrimitive.js:925:13)
    at visitTile (https://cesiumjs.org/Cesium/Source/Scene/QuadtreePrimitive.js:813:13)
    at visitIfVisible (https://cesiumjs.org/Cesium/Source/Scene/QuadtreePrimitive.js:946:20)
    at visitVisibleChildrenNearToFar (https://cesiumjs.org/Cesium/Source/Scene/QuadtreePrimitive.js:925:13)
    at visitTile (https://cesiumjs.org/Cesium/Source/Scene/QuadtreePrimitive.js:813:13)
    at visitIfVisible (https://cesiumjs.org/Cesium/Source/Scene/QuadtreePrimitive.js:946:20)
    at visitVisibleChildrenNearToFar (https://cesiumjs.org/Cesium/Source/Scene/QuadtreePrimitive.js:916:17)
```

**Comment by OmarShehata** [comment]
I think this is the same issue as https://github.com/AnalyticalGraphicsInc/cesium/issues/5837 in that the underlying problem that causes the crash is that the camera goes underground. If you change:

```
 center:Cesium.Cartesian3.fromDegrees(111,33)
```

to 

```
 center:Cesium.Cartesian3.fromDegrees(111,33, 1)
```

It will no longer crash. But since we do want to allow the camera to go underground eventually, I think having it as a separate bug makes sense.

**Comment by hpinkos** [comment]
This appears to be fixed, but @Joyzen feel free to re-open this issue if you are still having trouble in the latest Cesium release
