### ISSUE TITLE
Cesium Inspector doesn't work without globe

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8712]
This may be expected behavior, and if so feel free to close. I just encountered it while testing for release and wanted to document it.

If you load this Sandcastle and quickly hit "show frustum planes" you'll get the following error:

https://sandcastle.cesium.com/index.html?src=Cesium%20Inspector.html&label=All

```
DeveloperError: normalized result is not a number
Error
    at new DeveloperError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:82:23)
    at Function.Cartesian3.normalize (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:1954:23)
    at https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:41888:35
    at computeTriangleAttributes (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:41921:17)
    at splitLongitudeTriangles (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:42093:25)
    at Object.GeometryPipeline.splitLongitude (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:42563:21)
    at geometryPipeline (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:97951:42)
    at Object.PrimitivePipeline.combineGeometry (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:98097:30)
    at loadSynchronous (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:99887:44)
    at Primitive.update (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:100514:21)
```

It looks as though this error is only thrown if this option is turned on before the globe loads. 

It looks like you can't turn on the Cesium Inspector if you disable the globe in the Viewer constructor. It will throw the following error if you try to do this:

```
Uncaught TypeError: Cannot set property 'depthTestAgainstTerrain' of undefined (on line 252774 of https://sandcastle.cesium.com/CesiumUnminified/Cesium.js)
```

**Comment by ggetz** [comment]
https://github.com/CesiumGS/cesium/issues/12419 brought up the fact that setting `depthTestAgainstTerrain` at all is unintuitive for users who aren't familiar with the intricacies of CesiumJS's rendering (i.e. most users). Users may see a inexplicable change in billboard or label rendering.

Should the inspector set this value at all? 

CC https://github.com/CesiumGS/cesium/issues/6991 which poses a similar question.
