### ISSUE TITLE
npm run coverage

### ISSUE THREAD

**Issue by emackey** [CesiumGS/cesium#8773]
After upgrading to NodeJS 12 LTS, I can't get `npm run test` or `npm run coverage` to work.  Is this known?

```
[15:14:50] Using gulpfile ~\Documents\Git\cesium\gulpfile.cjs
[15:14:50] Starting 'coverage'...
20 04 2020 15:14:50.214:ERROR [config]: Invalid config file!
  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\emackey\Documents\Git\cesium\Specs\karma.conf.js
require() of ES modules is not supported.
require() of C:\Users\emackey\Documents\Git\cesium\Specs\karma.conf.js from C:\Users\emackey\Documents\Git\cesium\node_modules\karma\lib\config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename karma.conf.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\emackey\Documents\Git\cesium\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.parseConfig (C:\Users\emackey\Documents\Git\cesium\node_modules\karma\lib\config.js:351:22)
    at new Server (C:\Users\emackey\Documents\Git\cesium\node_modules\karma\lib\server.js:66:24)
    at C:\Users\emackey\Documents\Git\cesium\gulpfile.cjs:735:17
    at coverage (C:\Users\emackey\Documents\Git\cesium\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:426:14)
    at runBound (domain.js:439:12)
    at asyncRunner (C:\Users\emackey\Documents\Git\cesium\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[15:14:50] The following tasks did not complete: coverage
```

**Comment by mramato** [comment]
Thanks @emackey probably just something we missed when adding support for Node 12/13 (without breaking 10).  Should be an easy fix.

**Comment by ggetz** [comment]
@emackey @mramato Is this still an issue given we're up to 16 LTS and coverage is working?

**Comment by emackey** [comment]
Issue is OBE.
