### ISSUE TITLE
"RangeError: Invalid array length at updateFrustums" when switching from 2D to 3D with pixelSize callback property

### ISSUE THREAD

**Issue by electricsam** [CesiumGS/cesium#8806]
I am trying to implement the scaling of points by distance in both 3D and 2D.  I cannot use the scaleByDistance property due to https://github.com/CesiumGS/cesium/issues/5259.  Instead I implemented a callback property for pixelSize, which does scale the points appropriately.  However, when switching from 2D to 3D an error occurs.  Switching from 3D to 2D works fine.

```
RangeError: Invalid array length
RangeError: Invalid array length
    at updateFrustums (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:228941:40)
    at View.createPotentiallyVisibleSet (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:229155:17)
    at executeCommandsInViewport (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:241459:18)
    at Scene.updateAndExecuteCommands (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:241264:17)
    at render (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:241971:19)
    at tryAndCatchError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:241990:17)
    at Scene.render (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:242065:17)
    at CesiumWidget.render (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:254715:29)
    at render (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:254040:36)
```

Here is a [sandcastle example](https://sandcastle.cesium.com/#c=hVTBjtowEP2VKZdNKtZhu+qlJFErKvVSqagr9ZSL1wxgrWNHtmGXIv69kzgJzrarBhSwZ96bN+OXCKOdh6PEZ7RQgMZnWKGTh5r96vaSG9EtV0Z7LjXam3RZadGhziB4jZbDhZCBgmLtJ8Rr/rI2UvsH+Rsp424xImup48h9HHgQXEm9+6I8RT58XNC1jBin4UW4KEGhB8Wdp0C/aoYKy6ukRr6g6qtGva64Uo9cPK2tadD6U5KkUJRwrjRAAPKuXuiXNcZJL41ecevNzvJmLwXbo9zt29oAcgtJC3hXFIOmNJDBsCYyrkL2NT+f9j9i4NoL4eKx9gQXQOVw5Cmng3qLJzqEKc+YPvb+k+tdXzs6gNup3uUUZlFxL484dvuffJq8QHJZVygGZ6OCVwhHyiNlV0vd/qu5t6dI+cmV632kJB0G0/50N4v+YPXEXJc5bDnNLe2MFh4ERnjyCDrGN5ukH2gH+hQbr5PwLTjIJefIn5d0PoCC2Sa4Vds/137dB0fjjoa2nv5xfc+21tRfcWcRXbKYQ/tNUxId1M7ms9z5k8IyVPss68ZYDwerEsYyj3VDB4EuezyIJ/RMONcC82wA5Rt5BLkpqtmrF0U1A0FmdxTZHlTXVDUr84zyJzBl+Ib88OOIVvFTm7K/K7+HTcZYntHyb5Q3hp5YGzH+AQ)

Browser: Chrome 81.0.4044.113

Operating System: macOS 10.15.4

**Comment by OmarShehata** [comment]
This is a common error that usually means you're feeding the engine bad data somewhere, see Ed's comment here: https://github.com/CesiumGS/cesium/issues/5811#issuecomment-346851587

> The "invalid array length" error is almost always the result of loading invalid data into Cesium

Your CallbackProperty returns an invalid value that causes this crash when the scene mode is morphing. Try printing out `camera.positionCartographic.height` to see this.

One way you can fix this is by preventing any update while the scene is morphing, like by adding this at the top of your callback property:

```
  if (viewer.scene.mode === Cesium.SceneMode.MORPHING) return;
```
