### ISSUE TITLE
NPM task 'build' is passed a non-Buffer / String variable.

### ISSUE THREAD

**Issue by TJKoury** [CesiumGS/cesium#8864]
[The method 'glslToJavaScript'](https://github.com/CesiumGS/cesium/blob/master/gulpfile.cjs#L1117) is [sometimes passed a Boolean](https://github.com/CesiumGS/cesium/blob/master/gulpfile.cjs#L332).  

Type conversions are not forced in Node 14.x and an exception is thrown.  Recommend testing for Boolean and handling accordingly.

**Comment by OmarShehata** [comment]
@TJKoury do you reproduce this just by running `npm run build` with Node 14.x ?

**Comment by TJKoury** [comment]
Tried it in Node 12.16.3, works (type coerced), behavior changed sometime between then and latest.

**Comment by LuminousPath** [comment]
Can confirm this bug, running `npm run build` on `v14.2.0` gives the error:
```
[14:42:18] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type boolean (false)
    at Object.writeFileSync (fs.js:1380:5)
    at glslToJavaScript (D:\Projects\Cesium\cesium\gulpfile.cjs:1331:6)
    at D:\Projects\Cesium\cesium\gulpfile.cjs:186:3
    at build (D:\Projects\Cesium\cesium\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:429:14)
    at runBound (domain.js:442:12)
    at asyncRunner (D:\Projects\Cesium\cesium\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by LuminousPath** [comment]
seems like the only thing requiring `minify` to be anything other than a boolean type is the `fs.writeFileSync` [here](https://github.com/CesiumGS/cesium/blob/master/gulpfile.cjs#L1330)

it's a simple fix to change this to `fs.writeFileSync(minifyStateFilePath, minify.toString());`

**Comment by TJKoury** [comment]
I'd recommend changing it to `if(typeof minify !=="boolean")`

**Comment by mramato** [comment]
We're happy to look at a PR if someone wants to open one. It doesn't really matter that much what gets written out, as long as functionality remains unchanged and it fixes the Node 14 issue.
