### ISSUE TITLE
Can't turn on shadows during viewer construction with Cesium OSM Buildings?

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#9137]
[Here's a Sandcastle](https://sandcastle.cesium.com/#c=dVJhb9owEP0rt3xpkIIJKW0HpWgq/bJpVacRbdKUL8Y+wKpjo7MTxKb+9zkJoHaj3+zze+/evXPNCWqFOyS4A4M7mKNTVcl+tLW4iER7n1vjuTJIRZTAn8IAeCQKlW9kayWRJkeiIOQef1rSMu8gcS9pCG7Dpd25CXiqsDAvvdvCdJ2Z0FY8M1ERofG5KjF4Och9qbTi5iFIshXZ8rOzH6/TYfCVpVnaT8f9dJRn2WQ0mlxd/iqiRvQk6wQaZFtSpfKqRse4lPEbm0+uvK+UlsqsXdw7Qxa8ROJspfe5jdu5JTqvDPfKmtPMc04+nLi5bE0+4JoQXdy/GbF0OE5glLLr8TBL4OYq7cKwpMKoB5VWF2CDvDFyUn3kfsO8/R6q3Lg4O1ABtsqLzXuw/hH3krQhQzPTghspuPMamwxya/WS033lvTXxRW7Xa42w6PZzkcCqMqJxFvc6a8dEWsAj3zI0fKlRhi19eO/ttm0eJdHU+b3GWecc4JMqt5Y8VKRjxgYey60Oi3CDZSWe0TPhXLOGBjodvKZOpapBybszPxKE5s6Fl1Wl9UL9xiKaTQcB/x9V2zbipxpJ830D2wxnX7siY2w6CNfzTN9l9o/yXw) with Cesium OSM Buildings. Click the button to toggle shadows, works fine.

If you enable shadows in the viewer constructor, you get:

```
An error occurred while rendering.  Rendering has stopped.
DeveloperError: normalized result is not a number
Error
    at new DeveloperError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:83:13)
    at Function.Cartesian3.normalize (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:2040:13)
    at Ellipsoid.geodeticSurfaceNormal (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:3606:23)
    at Ellipsoid.cartesianToCartographic (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:3699:18)
    at fitShadowMapToScene (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:267333:40)
    at ShadowMap.update (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:267565:9)
    at updateShadowMaps (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:282939:17)
    at updateAndRenderPrimitives (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:282962:5)
    at executeCommandsInViewport (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:282734:7)
    at Scene.updateAndExecuteCommands (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:282477:7)
```

**Comment by mramato** [comment]
FYI, this only happens at certain times of the day (I just tried to reproduce and it didn't work).  Basically you need shadows to actually be cast in the scene.  I edited the original link to have the demo always crash.

**Comment by mramato** [comment]
This looks like a clear cut "something isn't initialized yet" bug which cascades into NaNs.

**Comment by jtorresfabra** [comment]
I've tracked this to be a bug in this condition https://github.com/CesiumGS/cesium/blob/master/Source/Scene/View.js#L322. 
In fact is not very clear for me what the intention is, as the condition is difficult to read. The bug happens when commnadFar has a negative value. 

Rewritting this condition to something like the below code fixes the crash:

```
(!(pass === Pass.GLOBE && commandNear < -100.0 && commandFar > 100.0) && commandFar > 0.0)
```
I don't feel comfortable changing this code without more knowledge. However I'm inclined to think the condition is not correct as it is, or at least it is difficult to understand what it does. Maybe it could be rewritten in a friendlier way.

Probably @IanLilleyT (sorry for the git blame) could give more insights about it.

cc: @lilleyse

**Comment by IanLilleyT** [comment]
This is more for @lilleyse . I was the last one to modify this file, and may have even introduced a bug in the process (do we know when this bug started happening?), but I'm not familiar enough with the shadow mapping system to know if there are any downsides to your fix

**Comment by lilleyse** [comment]
Thanks for investigating this @jtorresfabra. That helped my narrow down the bug fairly quickly. I opened https://github.com/CesiumGS/cesium/pull/9172.
