### ISSUE TITLE
RangeError: invalid array length

### ISSUE THREAD

**Issue by asypost** [CesiumGS/cesium#9170]
```
h.packCreateGeometryResults@http://localhost:9999/Workers/PrimitivePipeline-3064ff54.js:1:5326
@http://localhost:9999/Workers/createGeometry.js:1:977
l/e<@http://localhost:9999/Workers/when-54c2dc71.js:1:322
e/<@http://localhost:9999/Workers/when-54c2dc71.js:1:683
v@http://localhost:9999/Workers/when-54c2dc71.js:1:1808
t@http://localhost:9999/Workers/when-54c2dc71.js:1:819
o@http://localhost:9999/Workers/when-54c2dc71.js:1:986
t/<@http://localhost:9999/Workers/when-54c2dc71.js:1:1674
l/e<@http://localhost:9999/Workers/when-54c2dc71.js:1:322
e/<@http://localhost:9999/Workers/when-54c2dc71.js:1:683
v@http://localhost:9999/Workers/when-54c2dc71.js:1:1808
t@http://localhost:9999/Workers/when-54c2dc71.js:1:819
o@http://localhost:9999/Workers/when-54c2dc71.js:1:986
l/e<@http://localhost:9999/Workers/when-54c2dc71.js:1:322
e/<@http://localhost:9999/Workers/when-54c2dc71.js:1:693
v@http://localhost:9999/Workers/when-54c2dc71.js:1:1808
t@http://localhost:9999/Workers/when-54c2dc71.js:1:819
o@http://localhost:9999/Workers/when-54c2dc71.js:1:986
l/e<@http://localhost:9999/Workers/when-54c2dc71.js:1:322
e/<@http://localhost:9999/Workers/when-54c2dc71.js:1:693
v@http://localhost:9999/Workers/when-54c2dc71.js:1:1808
t@http://localhost:9999/Workers/when-54c2dc71.js:1:819
o@http://localhost:9999/Workers/when-54c2dc71.js:1:986
l/e<@http://localhost:9999/Workers/when-54c2dc71.js:1:322
e/<@http://localhost:9999/Workers/when-54c2dc71.js:1:693
v@http://localhost:9999/Workers/when-54c2dc71.js:1:1808
t@http://localhost:9999/Workers/when-54c2dc71.js:1:819
o@http://localhost:9999/Workers/when-54c2dc71.js:1:986
l/e<@http://localhost:9999/Workers/when-54c2dc71.js:1:322
e/<@http://localhost:9999/Workers/when-54c2dc71.js:1:693
v@http://localhost:9999/Workers/when-54c2dc71.js:1:1808
t@http://localhost:9999/Workers/when-54c2dc71.js:1:819
```

Browser: Firefox 81.0

Operating System:Windows 10 Pro 64 bit

**Comment by OmarShehata** [comment]
@asypost please provide a [Sandcastle](https://sandcastle.cesium.com/index.html?) reproducing the issue.

**Comment by asypost** [comment]
I also tried it on Chrome,which produced another issue:

```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Float64Array (<anonymous>)
    at Object.h.packCreateGeometryResults (http://localhost:9999/Workers/PrimitivePipeline-3064ff54.js:1:5326)
    at http://localhost:9999/Workers/createGeometry.js:1:977
    at a.e [as then] (http://localhost:9999/Workers/when-54c2dc71.js:1:322)
    at http://localhost:9999/Workers/when-54c2dc71.js:1:683
    at v (http://localhost:9999/Workers/when-54c2dc71.js:1:1807)
    at t (http://localhost:9999/Workers/when-54c2dc71.js:1:819)
    at Object.o [as resolve] (http://localhost:9999/Workers/when-54c2dc71.js:1:986)
    at http://localhost:9999/Workers/when-54c2dc71.js:1:1674
```
I'll provide an URL next day.

**Comment by asypost** [comment]
This is the [Demo](http://36.7.136.16:9000/index.html) which produces the issue.

**Comment by OmarShehata** [comment]
@asypost can you please reproduce the issue in [Sandcastle](https://sandcastle.cesium.com/index.html?) ?

**Comment by asypost** [comment]
Sorry,I thought a demo close to the real production was more meaningful. 

Here's the[ Sandcastle](https://sandcastle.cesium.com/#c=nVRbb5swFP4rVp6oGhnoVSFptSppq0nrNq1RX8o0OXAAb46NbJM0nfLfZ2MgZOmkbQ+gc/nO9TuwIhKtKKxBoivEYY2moGi1xE+1zYsHSa1PBdeEcpDx4Ggc85hnoJPCuAuty8j3Ty/wJQ7NO7yIRkEQ+CnRBH9XgpuAmGNdAPeyiieaCo48CaoUXMHRz5gjhCToSnLUWus4z9bZHsR6NrELSwxWMMBM5KYRJkhKee76Q8iq31Yq0aqOwDP7enqczntukmU9583dnSvp5mt73UO6wiuzM+CaagrKbM2tD7eWOr99MiE9C6UGE4wpmqC6GAOe62KM6PFxM36dkGpYGqCFPNOvY+doc2KSpl4DNs2TBbCoUxHS8KIjmwB/vHm4be3bYSuVQlE7TNSQOyVSG4nwU5xJsZxBLgGUV2f4cD+fDZ00n8+OuhwLythCEJn2C9MlySH68xUUojJ0lpaW4S5qTVNdROFFz1QAzQttbF3zTtg6uoy2PWRlR+9f82IhpaBcW8CzW/M+T+i/iHI5cVmpwvv3JXdD9mbYmBr79De7aK5ig0vBNsx8k/sf7ufGei9JWdBE7c5GFWIdaVnBwV0oFDUTdC7H0UmnL4kGSQnrTkgwIfGX21mHSKHUxR2h7KGFVjyFzLSSdpiEEaVoRhNiy843JURoVyOXhFeMSDNchAIchJdn56cno5PzcDQ6M8L5cDcKScVaGVRnIjKp84X9YstyLu6lMI3sD/763rT2EgW9I9sOhoOJ0hsG1y3qHV2WQmpUSeZh7Bu6SmZmU/6iSn6AxolSLSUTvx86SekK0fTqjb+nW4HxZBVjj/QV4sH1xDf4g9Dmh/ZpBZKRjYUV4fUHZ8QYT3yjvh2phWALIn/L/As)。I don't have a HTTPS Server so you need to change the **security.mixed_content.block_active_content** to **false** in firefox **about:config** page.

Here is the error snapshot on Firefox 81.0(64 bit) Windows 10. 
![image](https://user-images.githubusercontent.com/1658213/94353766-9ee0c080-00a7-11eb-877b-c34af874ba89.png)



Thank you for your patient.

**Comment by swiss-knight** [comment]
I am also experiencing such error:

```
An error occurred while rendering. Rendering has stopped.

RangeError: invalid array length

updateFrustums@http://localhost:8081/Build/Cesium/Cesium.js:1:2877049
View.prototype.createPotentiallyVisibleSet@http://localhost:8081/Build/Cesium/Cesium.js:1:2879945
executeCommandsInViewport@http://localhost:8081/Build/Cesium/Cesium.js:1:3063988
Scene.prototype.updateAndExecuteCommands@http://localhost:8081/Build/Cesium/Cesium.js:1:3061280
render@http://localhost:1338/Build/Cesium/Cesium.js:1:3073789
tryAndCatchError@http://localhost:8081/Build/Cesium/Cesium.js:1:3074027
Scene.prototype.render@http://localhost:8081/Build/Cesium/Cesium.js:1:3075886
CesiumWidget.prototype.render@http://localhost:8081/Build/Cesium/Cesium.js:1:3323706
e@http://localhost:1338/Build/Cesium/Cesium.js:1:3309560
FrameRequestCallback*requestAnimationFramePolyFill@http://localhost:1338/Build/Cesium/Cesium.js:1:810846
e@http://localhost:1338/Build/Cesium/Cesium.js:1:3309570
FrameRequestCallback*requestAnimationFramePolyFill@http://localhost:1338/Build/Cesium/Cesium.js:1:810846
e@http://localhost:1338/Build/Cesium/Cesium.js:1:3309570
FrameRequestCallback*requestAnimationFramePolyFill@http://localhost:1338/Build/Cesium/Cesium.js:1:810846
e@http://localhost:1338/Build/Cesium/Cesium.js:1:3309570
(... the two last lines repeats a lot of time)
```

I am using Cesium 1.73 locally.     
I am not able to figure out what's wrong, because every thing is fine, I can interact with my app, draw new features, and so on, but whenever I start rotating with Ctrl+Left-Mouse-Click, the error pops out and the app stops responding.

Both Firefox (latest) and Brave browser (latest) send the same error.

**Comment by GatorScott** [comment]
Removing the setting of granularity eliminates the crash for me.  This doesn't make sense yet because the documentation seems to say that granularity won't be applied if "arcType is not ArcType.NONE and clampToGround is false".  Either way I would not expect setting granularity to its advertised default value to cause any problems.

**Comment by asypost** [comment]
> Removing the setting of granularity eliminates the crash for me. This doesn't make sense yet because the documentation seems to say that granularity won't be applied if "arcType is not ArcType.NONE and clampToGround is false". Either way I would not expect setting granularity to its advertised default value to cause any problems.

Thanks, It works.
