### ISSUE TITLE
Render crash when creating `polylineVolume` with very close points

### ISSUE THREAD

**Issue by ulrichson** [CesiumGS/cesium#9249]
When creating a `polylineVolume` with very close points following error happens:

```
An error occurred while rendering.  Rendering has stopped.
DeveloperError: normalized result is not a number
Error
    at new DeveloperError (https://sandcastle.cesium.com/CesiumUnminified/Workers/Check-6c0211bc.js:62:13)
    at Function.Cartesian3.normalize (https://sandcastle.cesium.com/CesiumUnminified/Workers/Cartesian2-ea28baad.js:439:13)
    at Object.PolylineVolumeGeometryLibrary.computePositions (https://sandcastle.cesium.com/CesiumUnminified/Workers/PolylineVolumeGeometryLibrary-60333c48.js:453:37)
    at Function.PolylineVolumeGeometry.createGeometry (https://sandcastle.cesium.com/CesiumUnminified/Workers/createPolylineVolumeGeometry.js:452:89)
    at createPolylineVolumeGeometry (https://sandcastle.cesium.com/CesiumUnminified/Workers/createPolylineVolumeGeometry.js:477:35)
    at createGeometry (https://sandcastle.cesium.com/CesiumUnminified/Workers/createGeometry.js:60:32)
    at callAndWrap (https://sandcastle.cesium.com/CesiumUnminified/Workers/createTaskProcessorWorker.js:61:25)
    at https://sandcastle.cesium.com/CesiumUnminified/Workers/createTaskProcessorWorker.js:107:9
```

I tried to dig into the issue:

- It happens when `forward = Cartesian2.Cartesian3.normalize(forward, forward)` is called because `nextPosition` and `position` are equal and thus `forward` becomes `0` (https://github.com/CesiumGS/cesium/blob/1.75/Source/Core/PolylineVolumeGeometryLibrary.js#L403)
- positions are altered with `scaleToSurface` and maybe due to the conversion / float precision some points become equal and the path has duplicates (prior in https://github.com/CesiumGS/cesium/blob/1.75/Source/Core/PolylineVolumeOutlineGeometry.js#L272 duplicates should be removed, but other might get re-introduced again)
- The problems seems to be related to points with same lat / lon but slightly different height in the example below (when the last point is removed it works, although it has a different position)

Sandcastle example:

https://sandcastle.cesium.com/#c=hZNbb9MwFMe/ylGfUlbc9JKkXrMK1CHxAEIaaC+EBy89bS0cO7KdTh3qd8fOrd0FkQfHOf79z9U5MA0Hjo+o4QYkPsIaDa8Kcl/bgmyQ199rJS3jEnU2GC4zmcmD05XM7p3qZyYB3k8mUxJNQxrORxDNyYIm8dxt53FEwkUYTpLRJbZIzlhEWyyilMa0eaLneBz3eDxr8Tmli+T/2IzSJJO/6qy3lcwtVxJyVZSVxTXXucBAsw2vzBD+eGd1ZcpwzxlfnpcCbJWGwJ9xZwuX7pXCLPabq6tW2Wi9M1Yr21Z+dW0iVt019oAPlw3cByFlZfZBY4TLIayZtm7H5LQ/BWiShXdQ+82VCdqIw9G/IMNlD3VMu2mSOflFo620PKflTk71qOurQFBaZ0dD2GYT1PWWShyFuxT3SlQFXndN6B1cv6pjRrZaFbe404jmo9bs+Bn5bm9N4O9SV4DZs9K5ez6jSUjCDiiYRc2ZOAdQQmly9+m2Bk5uPTXXtM/+Sanihwpe1OKhwWiQGnsUuOpa84EXpdIWKi0CQsYWi1K4iGb8UOW/0ZLcmG6G6fhSmm74Afjm5o2/BnLBjHEn20qI7/wJs8EqHTv+lVQoNym5+3ZALdjRY/vJ6ktjJISkY/f5ttIqJR6YfuH5Lw

Browser: Chrome Version 87.0.4280.66 (Official Build) (64-bit)

Operating System: Ubuntu 18.04.4 LTS

**Comment by hpinkos** [comment]
Thanks for including the sandcastle example @ulrichson 
I was able to reproduce the crash on my machine
