### ISSUE TITLE
I use the toktx tool in Khronos texture tools to generate the KTX file. When I use it, I will report an error as follows:

### ISSUE THREAD

**Issue by herewaitting** [CesiumGS/cesium#9335]
.\toktx.exe --cubemap --t2  .\sky\sky.ktx .\sky\posX.jpg .\sky\negX.jpg .\sky\posY.jpg .\sky\negY.jpg .\sky\posZ.jpg .\sky\negZ.jpg

Browser: chrome  84.0.4147.105

Error loading specularEnvironmentMaps: RuntimeError: glInternalFormat is not a valid format.
Error
    at new RuntimeError (http://localhost:8080/Source/Core/RuntimeError.js:38:11)
    at parseKTX (http://localhost:8080/Source/Core/loadKTX.js:196:11)
    at http://localhost:8080/Source/Core/loadKTX.js:83:14
    at Promise.then (http://localhost:8080/Source/ThirdParty/when.js:194:34)
    at http://localhost:8080/Source/ThirdParty/when.js:295:13
    at processQueue (http://localhost:8080/Source/ThirdParty/when.js:645:4)
    at _resolve (http://localhost:8080/Source/ThirdParty/when.js:331:4)
    at promiseResolve (http://localhost:8080/Source/ThirdParty/when.js:357:11)
    at Promise.then (http://localhost:8080/Source/ThirdParty/when.js:194:34)
    at http://localhost:8080/Source/ThirdParty/when.js:296:7
Error loading specularEnvironmentMaps: RuntimeError: glInternalFormat is not a valid format.
Error
    at new RuntimeError (http://localhost:8080/Source/Core/RuntimeError.js:38:11)
    at parseKTX (http://localhost:8080/Source/Core/loadKTX.js:196:11)
    at http://localhost:8080/Source/Core/loadKTX.js:83:14
    at Promise.then (http://localhost:8080/Source/ThirdParty/when.js:194:34)
    at http://localhost:8080/Source/ThirdParty/when.js:295:13
    at processQueue (http://localhost:8080/Source/ThirdParty/when.js:645:4)
    at _resolve (http://localhost:8080/Source/ThirdParty/when.js:331:4)
    at promiseResolve (http://localhost:8080/Source/ThirdParty/when.js:357:11)
    at Promise.then (http://localhost:8080/Source/ThirdParty/when.js:194:34)
    at http://localhost:8080/Source/ThirdParty/when.js:296:7

![negX](https://user-images.githubusercontent.com/22114883/105154891-f5857500-5b44-11eb-8837-99be94d171f8.jpg)
![negY](https://user-images.githubusercontent.com/22114883/105154898-f7e7cf00-5b44-11eb-8a55-558ba2fd7afc.jpg)
![negZ](https://user-images.githubusercontent.com/22114883/105154900-f8806580-5b44-11eb-9525-eb2243992ae6.jpg)
![posX](https://user-images.githubusercontent.com/22114883/105154904-f8806580-5b44-11eb-800b-b10b5c15c216.jpg)
![posY](https://user-images.githubusercontent.com/22114883/105154905-f9b19280-5b44-11eb-9913-f682a0182582.jpg)
![posZ](https://user-images.githubusercontent.com/22114883/105154908-fa4a2900-5b44-11eb-88df-0d1985ba8a4f.jpg)

**Comment by ebogo1** [comment]
@herewaitting Thanks for reporting this issue. We have since deprecated KTX 1.0 in favor of KTX 2.0. I'll close this for now but if you are still seeing the issue please feel free to reopen this or submit a new one!
