### ISSUE TITLE
EntityClustering crashes when DataSource is removed

### ISSUE THREAD

**Issue by vividos** [CesiumGS/cesium#9336]
I'm using some parts of code from the Clustering Sandcastle demo. In my application I have several DataSources (one `CustomDataSource`, and potentially some `CzmlDataSources`). I'd like to cluster the elements in the data sources (mostly pins, but also points and labels) and I'm creating one `Cesium.EntityCluster` object:

https://github.com/vividos/WhereToFly/blob/5cb867c4c9e89e7c6ab0660f5dcd2b13f05b0a45/src/App/Resources/Assets/map/mapView3D.js#L390

I'm setting the `EntityCluster` object for my `CustomDataSource`:
https://github.com/vividos/WhereToFly/blob/5cb867c4c9e89e7c6ab0660f5dcd2b13f05b0a45/src/App/Resources/Assets/map/mapView3D.js#L265

Now when adding CZML files to my map view, I'm also setting the clustering property of the just loaded `CzmlDataSource`:
https://github.com/vividos/WhereToFly/blob/5cb867c4c9e89e7c6ab0660f5dcd2b13f05b0a45/src/App/Resources/Assets/map/mapView3D.js#L963

Clustering works well, and I can even switch it on/off globally.

Now the map view crashes and stops rendering when I remove a CZML data source again:
https://github.com/vividos/WhereToFly/blob/5cb867c4c9e89e7c6ab0660f5dcd2b13f05b0a45/src/App/Resources/Assets/map/mapView3D.js#L1125

As soon as the scene is re-rendered, the following call stack is shown (CesiumUnminified is used here):
```
An error occurred while rendering. Rendering has stopped.
TypeError: Unable to get property '_textureAtlas' of undefined or null reference
TypeError: Unable to get property '_textureAtlas' of undefined or null reference
   at Billboard.prototype.setImage (.../Cesium/Cesium.js:158459:5)
   at image.set (.../Cesium/Cesium.js:158149:11)
   at BillboardVisualizer.prototype.update (.../Cesium/Cesium.js:93141:9)
   at DataSourceDisplay.prototype.update (.../Cesium/Cesium.js:204161:9)
   at Viewer.prototype._onTick (.../Cesium/Cesium.js:300870:5)
   at Event.prototype.raiseEvent (.../Cesium/Cesium.js:14081:9)
   at Clock.prototype.tick (.../Cesium/Cesium.js:50418:5)
   at CesiumWidget.prototype.render (.../Cesium/Cesium.js:294541:7)
   at render (.../Cesium/Cesium.js:293797:13)
```
(I shortened the paths a bit).

I also tried setting the `clustering` property to `undefined` or to a newly created `Cesium.EntityCluster` object, but the crash stays the same.

I even tried to "force a re-cluster", just like shown in the sandcastle demo, setting `pixelRange` to 0 and back to the last value.

From the documentation I got the idea that sharing `EntityCluster` objects is possible, but maybe I'm just doing something wrong. Thanks for helping in advance!

Browser: This occurs in the UWP WebView (I think it's based on Edge, but I'm not sure), and in the Android WebView, which uses the installed Chrome.

Operating System: Windows 10 / Android 11

**Comment by vividos** [comment]
I debugged my case here today, and I think that sharing `EntityCluster` objects is currently not supported by `DataSource` objects. The reason for this is this line:

https://github.com/CesiumGS/cesium/blob/b3334483f6c543ce1f16a2e41d7c8c641f137567/Source/DataSources/DataSourceDisplay.js#L454-L455

Here, the `EntityCluster` is removed from the `PrimitiveCollection` when the `DataSource` is removed from the `DataSourceCollection` in the viewer. Since the `PrimitiveCollection` destroys all primitives, the `EntityCluster` is also destroyed. In the next render loop, the `EntityCluster` is accessed by other `DataSource` objects, which is destroyed now.

My workaround for this is to make my only `EntityCluster` instance un-destroyable (by setting a new empty `destroy()` function). That seems to work.

The fix would be to give the `EntityCluster` object some sort of `sharedInstance` property and when true, not remove it from the primitives collection (or don't add it in the first place, but give it a distinct Display object that takes care of rendering).

Alternatively the documentation should be changed to clarify that `EntityCluster` object indeed can't be shared among data sources, but that would prevent clustering from working across data sources. The documentation can be found here:

https://github.com/CesiumGS/cesium/blob/b3334483f6c543ce1f16a2e41d7c8c641f137567/Source/DataSources/DataSource.js#L84

**Comment by srothst1** [comment]
@vividos Thank you for submitting such a detailed issue. I am currently implementing a solution. To ensure that my solution solves the correct bug, it would be helpful if you provided a sandcastle demo that outlines the specific problem. Let me know if this is possible.

**Comment by vividos** [comment]
Here's a Sandcastle that shows the error; I thought the bug was triggered only by clicking on the "Remove data source A" button, but it crashes immediately after init, since there's no way to let the data source know that the `EntityCluster` object is shared.

https://sandcastle.cesium.com/#c=rZRdjxIxFIb/ysncMCRjB8IiiCyRAaIXKAZ2jSaTbMrMARo7LWk7s6LZ/26nQ/hajBq943y8p+d92qGgCgqGj6jgFgQ+wgg1yzPyyeX82EtcPJLCUCZQxV79dSxiUVhdwnNtUDGxPtdOhGFmN6qq/o9YAKCgS45pD4zKMSgzGRMss4OrrgX7jj1ou8qWfUM+p2JtMzeNWDwdT0ypoQuZqwSH50eO7BSZjQ9lvzaslbITATlb9xjYrgoAOTZrQtPUPxFXK5xOw9Ik23c6j8zaq32uVR6ktlUpeocFqTL2FxUtslJ2U1wrRO2/6LRJ+1Wn0wmsVdJodbut+n4AE6YHbjBAIrlUx1llROaTcVBVHbCKYHef2iBbb8wcV6hQJHiQvjvPk9F0+P7jw93s4e18dv9hXIqfgj1ygEvo0e+gRxfQo3+BHl1Cj34F/ctfQu82SDuAVps0b/6UdjS9nzzH3Xz5H3nHYkFFmlBtOJYG76TkS6qi3Bgp7Jc4x0wW6K4DtAMCw9gLYJWLpLTt193+V7gqp7x8z+5QL/D62uw4DiojAG9YtpXKQK64T0hoMNtyajGGyzz5ioYkWlevA6Afnkr7KSvsfdxe+c+wN0+1tpVVzh262Bv0Q9v/TMolTe37mBWoON2VbZvmYFolCSH90IbXlabCdTH5Jw

**Comment by srothst1** [comment]
@vividos Thanks for sharing the sandcastle demo with me - there are clearly a few issues here. It seems like updating `entityCluster` in `cesium/Source/DataSources/DataSourceDisplay.js` may not be sufficient to solve the entire problem.
