### ISSUE TITLE
About cesium1.70  run build error

### ISSUE THREAD

**Issue by chenlongfromchina** [CesiumGS/cesium#9435]
:exclamation: Please use the [community forum](https://community.cesium.com/) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:
> cesium@1.70.0 build E:\02-code\cesium-1.70
> gulp build

[10:08:45] Using gulpfile E:\02-code\cesium-1.70\gulpfile.cjs
[10:08:45] Starting 'build'...
[10:08:45] 'build' errored after 3.56 ms
[10:08:45] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type boolean (false)
    at Object.writeFileSync (fs.js:1380:5)
    at glslToJavaScript (E:\02-code\cesium-1.70\gulpfile.cjs:1313:6)
    at E:\02-code\cesium-1.70\gulpfile.cjs:187:3
    at build (E:\02-code\cesium-1.70\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:429:14)
    at runBound (domain.js:442:12)
    at asyncRunner (E:\02-code\cesium-1.70\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cesium@1.70.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cesium@1.70.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program Files\nodejs\node_cache\_logs\2021-03-19T02_08_45_702Z-debug.log

**Comment by dzungpng** [comment]
@chenlongfromchina Can you please provide some details about the node version and gulp version you are using?

**Comment by dzungpng** [comment]
Closing this issue as we have not heard back from the original poster. This seems like an issue with package versioning instead of CesiumJS. Please follow up if needed.
