### ISSUE TITLE
Cesium JS: scaleToGeodeticSurface.js:34 Uncaught DeveloperError {name: "DeveloperError", message: "cartesian is required.", stack: "Error↵

### ISSUE THREAD

**Issue by favourori** [CesiumGS/cesium#9454]
I upgraded my cesium version from v1.59 to v1.77. I have also updated all the deprecated constructors to the latest, but I keep running into this issue when I try to draw on my asset. Does anyone know what's causing this? Here's a screenshot for more context:

![AJ9HE](https://user-images.githubusercontent.com/8339261/112804941-48176c00-9075-11eb-8b21-2a07c4c1aef9.jpeg)

Here's the full error:
`An error occurred while rendering. Rendering has stopped.
TypeError: Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at Function.push../node_modules/cesium/Source/Core/PolygonGeometry.js.PolygonGeometry.createGeometry (http://127.0.0.1:8000/static/dist/npm.cesium-01ff433966601611e5b8.js:63652:22)
    at loadSynchronous (http://127.0.0.1:8000/static/dist/npm.cesium-01ff433966601611e5b8.js:243718:46)
    at Primitive.push../node_modules/cesium/Source/Scene/Primitive.js.Primitive.update (http://127.0.0.1:8000/static/dist/npm.cesium-01ff433966601611e5b8.js:244518:7)
    at ClassificationPrimitive.push../node_modules/cesium/Source/Scene/ClassificationPrimitive.js.ClassificationPrimitive.update (http://127.0.0.1:8000/static/dist/npm.cesium-01ff433966601611e5b8.js:181841:19)
    at GroundPrimitive.push../node_modules/cesium/Source/Scene/GroundPrimitive.js.GroundPrimitive.update (http://127.0.0.1:8000/static/dist/npm.cesium-01ff433966601611e5b8.js:203590:19)
    at PrimitiveCollection.push../node_modules/cesium/Source/Scene/PrimitiveCollection.js.PrimitiveCollection.update (http://127.0.0.1:8000/static/dist/npm.cesium-01ff433966601611e5b8.js:245299:19)`

**Comment by dzungpng** [comment]
From the screenshot, it looks like a conversion from Cartesian to Cartographic is being performed but the input to the function is not Cartesian. Could you post the code snippet that is giving the error?

**Comment by ggetz** [comment]
I'm closing this issue due to inactivity. If you believe this is still an issue, please feel free to re-open. Thanks!
