### ISSUE TITLE
npm run release fails

### ISSUE THREAD

**Issue by Kennnyoung** [CesiumGS/cesium#9542]
Hi all, I have cloned the repo to my local machine and run npm install as stated in the build guide.

However when I run npm run release, the following three types of errors happened:
1. [TSD-JSDoc] InspectorShared.js:17:0 Failed to find parent of doclet 'InspectorShared.createCheckbox' using memberof 'InspectorShared', this is likely due to invalid JSDoc.`

2. Source/Cesium.d.ts:1:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: DEPTH_BUFFER_BIT, STENCIL_BUFFER_BIT, COLOR_BUFFER_BIT, POINTS, LINES, LINE_LOOP, LINE_STRIP, TRIANGLES, TRIANGLE_STRIP, TRIANGLE_FAN, ZERO, ONE, SRC_COLOR, ONE_MINUS_SRC_COLOR, SRC_ALPHA, 
.
.
.
ONE_MINUS_SRC_ALPHA, DST_ALPHA, ONE_MINUS_DST_ALPHA, DST_COLOR, ONE_MINUS_DST_COLOR, SRC_ALPHA_SATURATE, FUNC_ADD, BLEND_EQUATION, BLEND_EQUATION_RGB, BLEND_EQUATION_ALPHA, FUNC_SUBTRACT, FUNC_REVERSE_SUBTRACT, BLEND_DST_RGB, BLEND_SRC_RGB, BLEND_DST_ALPHA, BLEND_SRC_ALPHA, CONSTANT_COLOR, ONE_MINUS_CONSTANT_COLOR, CONSTANT_ALPHA, ONE_MINUS_CONSTANT_ALPHA, BLEND_COLOR, ARRAY_BUFFER, ELEMENT_ARRAY_BUFFER, ARRAY_BUFFER_BINDING, ELEMENTTRANSFORM_FEEDBACK_,PRIMITIVES_WRITTEN, RASTERIZER_DISCARD, MPostProcessStageSampleMode, SceneMode, SceneTransforms, ShadowMode, SingleTileImageryProvider, StencilFunction, StencilOperation, TileCoordinatesImageryProvider, TileMapServiceImageryProvider, UrlTemplateImageryProvider, VerticalOrigin, WebMapServiceImageryProvider, WebMapTileServiceImageryProvider, createElevationBandMaterial, createOsmBuildings, createTangentSpaceDebugPrimitive, createWorldImagery, SvgPathBindingHandler, createCommand, AnimationViewModel, ProviderViewModel, Geocoder, SelectionIndicatorViewModel, Viewer, viewerCesium3DTilesInspectorMixin, viewerCesiumInspectorMixin, viewerDragDropMixin, viewerPerformanceWatchdogMixin
declare module "cesium" {

  ../../../node_modules/cesium/Source/Cesium.d.ts:1:1
     declare module "cesium" {
    Conflicts are in this file.

3. Source/Cesium.d.ts:5986:14 - error TS2649: Cannot augment module 'Event' with value exports because it resolves to a non-module entity.

5986 export class Event {

Does anyone know whats going on here? Any input is greatly appreciated!

**Comment by Kennnyoung** [comment]
I have been able to run npm run minifyRelease however the result Cesium.js file fails to render the viewer, the console in browser throws this error
`Cesium.js:1 An error occurred while rendering.  Rendering has stopped.
TypeError: Cannot read property 'undefined' of undefined
TypeError: Cannot read property 'undefined' of undefined
    at Object.ModelUtility.computeBoundingSphere (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:1304640)
    at Model.update (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:1531518)
    at Gltf3DTileContent.update (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:1565623)
    at Cesium3DTile.process (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:1975739)
    at processTiles (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:2008788)
    at Cesium3DTileset.prePassesUpdate (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:2009079)
    at PrimitiveCollection.prePassesUpdate (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:2179515)
    at prePassesUpdate (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:3228989)
    at tryAndCatchError (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:3234226)
    at Scene.render (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:3235715)`

**Comment by mramato** [comment]
1. The TSD-JSDoc errors are harmless.

2. `../../../node_modules/cesium/Source/Cesium.d.ts:1:1`

How are you cloning/building?  This looks like it's finding a type definition file in a random `node_modules` somewhere in your source tree or directory structure. Are you submoduling Cesium into some other repository or something?

* Can you confirm you are working with a clean clone of master?
* What version of Node.js are you using?

**Comment by Kennnyoung** [comment]
> 1. The TSD-JSDoc errors are harmless.
> 2. `../../../node_modules/cesium/Source/Cesium.d.ts:1:1`
> 
> How are you cloning/building? This looks like it's finding a type definition file in a random `node_modules` somewhere in your source tree or directory structure. Are you submoduling Cesium into some other repository or something?
> 
> * Can you confirm you are working with a clean clone of master?
> * What version of Node.js are you using?

Hi thank you for the reply! I cloned the master branch into a new folder inside the github folder auto created by github, it should be a clean clone imo.

Im using node v14.16.1

**Comment by mramato** [comment]
Something apparents to be wrong on your end.  Where is `../../../node_modules/cesium/Source/Cesium.d.ts:1:1` coming from?  If you follow the directory tree from where you are running release, what folder is it pointing to? It's definitely not part of the CesiumJS source tree.

If you're still having problems, you may behave better luck asking this question on http://community.cesium.com in case others have seen something similar.

**Comment by Kennnyoung** [comment]
> Something apparents to be wrong on your end. Where is `../../../node_modules/cesium/Source/Cesium.d.ts:1:1` coming from? If you follow the directory tree from where you are running release, what folder is it pointing to? It's definitely not part of the CesiumJS source tree.
> 
> If you're still having problems, you may behave better luck asking this question on http://community.cesium.com in case others have seen something similar.

Thank you so much! I have succeeded in running npm run release after deleting that folder. 

However when I run the Cesium.js file I got from that the browser console throws the following error,

`Cesium.js:1 An error occurred while rendering.  Rendering has stopped.
TypeError: Cannot read property 'undefined' of undefined
TypeError: Cannot read property 'undefined' of undefined
    at Object.ModelUtility.computeBoundingSphere (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:1304640)
    at Model.update (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:1531518)
    at Gltf3DTileContent.update (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:1565623)
    at Cesium3DTile.process (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:1975739)
    at processTiles (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:2008788)
    at Cesium3DTileset.prePassesUpdate (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:2009079)
    at PrimitiveCollection.prePassesUpdate (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:2179515)
    at prePassesUpdate (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:3228989)
    at tryAndCatchError (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:3234226)
    at Scene.render (http://localhost:8080/Source/cesium/Build/Cesium/Cesium.js:1:3235715)`

I was able to run the exact same code I wrote using the Cesium.js file I got from npm install in my own package.json

Would you mind giving any input on this?

**Comment by Kennnyoung** [comment]
I am closing this issue because I am able to solve it now. Just make sure you run npm run build before npm run minifyRelease. You should be able to use the Cesium.js file from that as normal.
