### ISSUE TITLE
About cesimu-1.80 build error in nodejs14.4.0

### ISSUE THREAD

**Issue by pooii2006** [CesiumGS/cesium#9621]
gulp -v 
CLI version: 2.3.0
Local version: 4.0.2
PS E:\LibCode\cesium\cesium-1.80> npm run build

> cesium@1.80.0 build
> gulp build

[10:24:05] Using gulpfile E:\LibCode\cesium\cesium-1.80\gulpfile.cjs
[10:24:05] Starting 'build'...
[10:24:05] 'build' errored after 702 ms
[10:24:05] Error: Unexpected token
    at error (E:\LibCode\cesium\cesium-1.80\node_modules\rollup\dist\shared\rollup.js:5309:30)
    at Module.error (E:\LibCode\cesium\cesium-1.80\node_modules\rollup\dist\shared\rollup.js:9765:16)
    at Module.tryParse (E:\LibCode\cesium\cesium-1.80\node_modules\rollup\dist\shared\rollup.js:10169:25)
    at Module.setSource (E:\LibCode\cesium\cesium-1.80\node_modules\rollup\dist\shared\rollup.js:10068:24)
    at ModuleLoader.addModuleSource (E:\LibCode\cesium\cesium-1.80\node_modules\rollup\dist\shared\rollup.js:18451:20) 
    at async ModuleLoader.fetchModule (E:\LibCode\cesium\cesium-1.80\node_modules\rollup\dist\shared\rollup.js:18507:9)
    at async Promise.all (index 17)
PS E:\LibCode\cesium\cesium-1.80> 
when I change nodejs version to v12，this error will disappear

[词典] | disappear
-- | --

**Comment by ebogo1** [comment]
cc @mramato Any ideas on this one?

**Comment by mramato** [comment]
@ebogo1 for issues like this you can just check out 1.80 (`git checkout 1.80`) and then build with node 14 (`nvm use 14` assuming it's not your default) and that makes it easy to confirm whether it works or not. (Always git clean when switching versions like this).

@pooii2006, in this case, Cesium 1.80 builds fine for me with Node 14, but it looks like you may be trying to build out of the release zip?  Or are you cloning from Git? We do not support rebuilding Cesium out of the release zip.

In general there is no reason to build Cesium unless you are working on Cesium itself.

If you still have questions, I would recommend asking for additional help on our community forum https://community.cesium.com
