### ISSUE TITLE
Intermittent CI test failures for ApproximateTerrainHeights

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#9672]
I've noticed the same CI failures on multiple runs related to `ApproximateTerrainHeights` and "Cesium is not defined" error.

```
[20:25:51] Starting 'test'...
  Core/ApproximateTerrainHeights
    ✗ initializes
	ReferenceError: Cesium is not defined
	    at createDefaultMatchers (Build/Specs/karma-main.js:690:9)
	    at Env.<anonymous> (Build/Specs/karma-main.js:1019:24)
	    at UserContext.<anonymous> (Build/Specs/karma-main.js:1184:36)
	    at <Jasmine>
	ReferenceError: Cesium is not defined
	    at Build/Specs/Specs.js:15:7
	    at UserContext.<anonymous> (Build/Specs/karma-main.js:1089:24)
	    at <Jasmine>
    ✗ getMinimumMaximumHeights computes minimum and maximum terrain heights
	ReferenceError: Cesium is not defined
	    at createDefaultMatchers (Build/Specs/karma-main.js:690:9)
	    at Env.<anonymous> (Build/Specs/karma-main.js:1019:24)
	    at UserContext.<anonymous> (Build/Specs/karma-main.js:1184:36)
	    at <Jasmine>
	ReferenceError: Cesium is not defined
	    at Build/Specs/Specs.js:21:20
	    at UserContext.<anonymous> (Build/Specs/karma-main.js:1089:24)
	    at <Jasmine>
    ✗ getMinimumMaximumHeights throws with no rectangle
	ReferenceError: Cesium is not defined
	    at createDefaultMatchers (Build/Specs/karma-main.js:690:9)
	    at Env.<anonymous> (Build/Specs/karma-main.js:1019:24)
	    at UserContext.<anonymous> (Build/Specs/karma-main.js:1184:36)
	    at <Jasmine>
	TypeError: expect(...).toThrowDeveloperError is not a function
	    at Build/Specs/Specs.js:37:10
	    at UserContext.<anonymous> (Build/Specs/karma-main.js:1089:24)
	    at <Jasmine>
    ✗ getMinimumMaximumHeights throws if ApproximateTerrainHeights was not initialized first
	ReferenceError: Cesium is not defined
	    at createDefaultMatchers (Build/Specs/karma-main.js:690:9)
	    at Env.<anonymous> (Build/Specs/karma-main.js:1019:24)
	    at UserContext.<anonymous> (Build/Specs/karma-main.js:1184:36)
	    at <Jasmine>
	ReferenceError: Cesium is not defined
	    at Build/Specs/Specs.js:41:21
	    at UserContext.<anonymous> (Build/Specs/karma-main.js:1089:24)
	    at <Jasmine>
    ✗ getBoundingSphere computes a bounding sphere
	ReferenceError: Cesium is not defined
	    at createDefaultMatchers (Build/Specs/karma-main.js:690:9)
	    at Env.<anonymous> (Build/Specs/karma-main.js:1019:24)
	    at UserContext.<anonymous> (Build/Specs/karma-main.js:1184:36)
	    at <Jasmine>
	ReferenceError: Cesium is not defined
	    at Build/Specs/Specs.js:52:20
	    at UserContext.<anonymous> (Build/Specs/karma-main.js:1089:24)
	    at <Jasmine>
    ✗ getBoundingSphere throws with no rectangle
	ReferenceError: Cesium is not defined
	    at createDefaultMatchers (Build/Specs/karma-main.js:690:9)
	    at Env.<anonymous> (Build/Specs/karma-main.js:1019:24)
	    at UserContext.<anonymous> (Build/Specs/karma-main.js:1184:36)
	    at <Jasmine>
	TypeError: expect(...).toThrowDeveloperError is not a function
	    at Build/Specs/Specs.js:72:10
	    at UserContext.<anonymous> (Build/Specs/karma-main.js:1089:24)
	    at <Jasmine>
    ✗ getBoundingSphere throws if ApproximateTerrainHeights was not initialized first
	ReferenceError: Cesium is not defined
	    at createDefaultMatchers (Build/Specs/karma-main.js:690:9)
	    at Env.<anonymous> (Build/Specs/karma-main.js:1019:24)
	    at UserContext.<anonymous> (Build/Specs/karma-main.js:1184:36)
	    at <Jasmine>
	ReferenceError: Cesium is not defined
	    at Build/Specs/Specs.js:76:21
	    at UserContext.<anonymous> (Build/Specs/karma-main.js:1089:24)
	    at <Jasmine>
```

**Comment by ggetz** [comment]
@lilleyse Is this still an issue? This seems like an issue with the test tooling rather than an unreliable test.

**Comment by lilleyse** [comment]
I haven't seen this in a while, so it's ok to close. We can reopen if it shows up again.
