### ISSUE TITLE
Broken example sandcastle for 'CZML Model Articulations'

### ISSUE THREAD

**Issue by fc** [CesiumGS/cesium#9855]
Your sandcastle example:
https://sandcastle.cesium.com/?src=CZML%20Model%20Articulations.html&label=CZML

The error says:
```
RuntimeError: Failed to load model: https://assets.agi.com/models/launchvehicle.glb
undefined
Error
    at new RuntimeError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:6891:13)
    at https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:140774:34
    at Promise.then (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:15824:35)
    at https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:15904:15
    at processQueue (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:16254:6)
    at _resolve (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:15940:6)
    at promiseReject (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:15973:13)
    at Promise.then (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:15824:35)
    at https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:15905:9
    at processQueue (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:16254:6)
```

When I load the GLB URL in the browser directly it seems to load fine.. definitely not obvious what the issue is.

**Comment by fc** [comment]
It still doesn't work for me -- guess it will get deployed later on?

**Comment by hpinkos** [comment]
@fc the fix will be deployed to sandcastle.cesium.com with the next release.  In the meantime, if you'd like to test it out, you can open the demo and replace `"https://assets.agi.com/models/launchvehicle.glb"` with `"https://cesium.com/public/SandcastleSampleData/launchvehicle.glb"`
