### ISSUE TITLE
Cannot read property latitude/longitude of underfined.

### ISSUE THREAD

**Issue by Renari** [CesiumGS/cesium#9951]
Sandcastle example:

Browser:

Operating System:

Not currently able to reproduce in Sandcastle.

```
TypeError: Cannot read properties of undefined (reading 'longitude')
    at GeographicProjection.project (webpack-internal:///./node_modules/cesium/Source/Core/GeographicProjection.js:65:24)
    at Object.Transforms.wgs84To2DModelMatrix (webpack-internal:///./node_modules/cesium/Source/Core/Transforms.js:1136:38)
    at updateNodeHierarchyModelMatrix (webpack-internal:///./node_modules/cesium/Source/Scene/Model.js:4349:79)
    at Model.update (webpack-internal:///./node_modules/cesium/Source/Scene/Model.js:5630:7)
    at Batched3DModel3DTileContent.update (webpack-internal:///./node_modules/cesium/Source/Scene/Batched3DModel3DTileContent.js:480:9)
    at Cesium3DTile.process (webpack-internal:///./node_modules/cesium/Source/Scene/Cesium3DTile.js:1951:17)
    at processTiles (webpack-internal:///./node_modules/cesium/Source/Scene/Cesium3DTileset.js:2335:14)
    at Cesium3DTileset.prePassesUpdate (webpack-internal:///./node_modules/cesium/Source/Scene/Cesium3DTileset.js:2197:3)
    at PrimitiveCollection.prePassesUpdate (webpack-internal:///./node_modules/cesium/Source/Scene/PrimitiveCollection.js:398:17)
    at prePassesUpdate (webpack-internal:///./node_modules/cesium/Source/Scene/Scene.js:3788:14)
```

This is happening while bundling Cesium with webpack, it seems to happen when the map projection is changed to 2D/Columbus and the camera is panned to the top/bottom/left/right of the screen. Panning to the top/bottom produces the same stack trace with a longitude trace, left/right produces the stack trace with a longitude trace.

**Comment by Virgil-N** [comment]
> Thanks for the report @Renari ! I would suggest that you take this to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help troubleshoot this further.
> 
> I'm closing this, but feel free to re-open if you find more information in regards to a bug.

I had the problem too.
